/* The following code was generated by JFlex 1.4.1 on 30/5/26, 19:14 */

package proyectofinalcompilador.Lexico;
import java_cup.runtime.Symbol;
import proyectofinalcompilador.Sintactico.sym;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 30/5/26, 19:14 from the specification file
 * <tt>src/proyectofinalcompilador/Lexico/LexerCup.flex</tt>
 */
public class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  7, 13,  0,  7,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     7, 42, 11,  0,  0, 48, 40,  0, 49, 50, 10, 47, 56,  6,  4,  8, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 46, 55, 43, 45, 44,  0, 
     0,  1,  1,  1,  1,  5,  1,  1,  1, 36,  1,  1,  1,  1, 37,  1, 
     1,  1,  1, 35, 38,  1,  1,  1,  1,  1,  1, 53, 12, 54,  0,  3, 
     0, 22, 14, 26, 19, 15, 20, 16, 33, 17,  1, 34, 25, 21, 18, 30, 
    23,  1, 27, 31, 29, 24, 28, 32,  1, 39,  1, 51, 41, 52,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\20\2\3\12\2\13\1\14\1\15\1\16"+
    "\1\1\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\1\1\3\1\1\1\27\1\30\1\6\2\0"+
    "\1\31\1\0\6\2\1\32\1\33\1\2\1\34\24\2"+
    "\1\12\1\13\1\3\2\0\4\2\1\35\2\2\1\36"+
    "\4\2\1\37\21\2\1\36\1\3\1\6\3\2\1\40"+
    "\3\2\1\41\4\2\1\42\3\2\1\43\3\2\1\44"+
    "\1\45\1\46\4\2\1\47\1\50\1\2\1\35\7\2"+
    "\1\51\3\2\1\52\4\2\1\53\2\2\1\54\1\55"+
    "\1\56\1\57\1\2\1\60\1\61\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\u018f"+
    "\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e\0\u0357"+
    "\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6\0\u051f"+
    "\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675\0\u063c\0\u063c"+
    "\0\u01c8\0\u06ae\0\u01c8\0\71\0\71\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\u06e7\0\u0720\0\u0759\0\71\0\71"+
    "\0\u0792\0\u07cb\0\u0201\0\71\0\u0804\0\u083d\0\u0876\0\u08af"+
    "\0\u08e8\0\u0921\0\u095a\0\u0993\0\162\0\u09cc\0\u0a05\0\u0a3e"+
    "\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06"+
    "\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce"+
    "\0\u0e07\0\u0e40\0\u0e79\0\71\0\71\0\u0eb2\0\u0eeb\0\u0f24"+
    "\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec"+
    "\0\u1125\0\u115e\0\u1197\0\u11d0\0\162\0\u1209\0\u1242\0\u127b"+
    "\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398\0\u13d1\0\u140a\0\u1443"+
    "\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u1560\0\u1599\0\162\0\u0eeb"+
    "\0\71\0\u15d2\0\u160b\0\u1644\0\162\0\u167d\0\u16b6\0\u16ef"+
    "\0\162\0\u1728\0\u1761\0\u179a\0\u17d3\0\162\0\u180c\0\u1845"+
    "\0\u187e\0\162\0\u18b7\0\u18f0\0\u1929\0\162\0\162\0\162"+
    "\0\u1962\0\u199b\0\u19d4\0\u1a0d\0\162\0\162\0\u1a46\0\162"+
    "\0\u1a7f\0\u1ab8\0\u1af1\0\u1b2a\0\u1b63\0\u1b9c\0\u1bd5\0\162"+
    "\0\u1c0e\0\u1c47\0\u1c80\0\162\0\u1cb9\0\u1cf2\0\u1d2b\0\u1d64"+
    "\0\162\0\u1d9d\0\u1dd6\0\162\0\162\0\162\0\162\0\u1e0f"+
    "\0\162\0\162\0\162\0\162";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\3\1\6\1\7"+
    "\1\10\1\7\1\11\1\12\1\2\1\7\1\13\1\14"+
    "\1\3\1\15\1\3\1\16\1\17\1\20\1\3\1\21"+
    "\1\3\1\22\1\23\1\24\1\25\1\26\1\3\1\27"+
    "\1\30\2\3\1\31\1\32\3\3\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\72\0\3\3"+
    "\1\0\1\3\10\0\32\3\22\0\1\54\1\4\1\54"+
    "\1\55\1\56\10\0\1\54\1\56\30\54\23\0\1\55"+
    "\74\0\1\57\46\0\1\60\22\0\1\7\1\0\1\7"+
    "\3\0\1\7\63\0\1\61\1\0\1\62\42\0\1\60"+
    "\70\0\1\60\13\0\13\63\1\64\1\65\1\0\53\63"+
    "\1\0\3\3\1\0\1\3\10\0\1\3\1\66\13\3"+
    "\1\67\2\3\1\70\10\3\1\71\22\0\3\3\1\0"+
    "\1\3\10\0\4\3\1\72\6\3\1\73\16\3\22\0"+
    "\3\3\1\0\1\3\10\0\4\3\1\74\1\3\1\75"+
    "\23\3\22\0\3\3\1\0\1\3\10\0\1\3\1\76"+
    "\16\3\1\77\11\3\22\0\3\3\1\0\1\3\10\0"+
    "\10\3\1\100\2\3\1\101\4\3\1\102\11\3\22\0"+
    "\3\3\1\0\1\3\10\0\10\3\1\103\21\3\22\0"+
    "\3\3\1\0\1\3\10\0\12\3\1\104\2\3\1\105"+
    "\14\3\22\0\3\3\1\0\1\3\10\0\20\3\1\106"+
    "\11\3\22\0\3\3\1\0\1\3\10\0\10\3\1\107"+
    "\2\3\1\110\7\3\1\111\6\3\22\0\3\3\1\0"+
    "\1\3\10\0\1\3\1\112\30\3\22\0\3\3\1\0"+
    "\1\3\10\0\10\3\1\113\7\3\1\114\11\3\22\0"+
    "\3\3\1\0\1\3\10\0\15\3\1\115\5\3\1\116"+
    "\6\3\22\0\3\3\1\0\1\3\10\0\17\3\1\117"+
    "\2\3\1\120\7\3\22\0\3\3\1\0\1\3\10\0"+
    "\23\3\1\121\6\3\22\0\3\3\1\0\1\3\10\0"+
    "\17\3\1\122\12\3\22\0\3\3\1\0\1\3\10\0"+
    "\27\3\1\123\2\3\71\0\1\124\71\0\1\124\74\0"+
    "\1\125\67\0\2\125\70\0\1\60\1\0\1\57\12\0"+
    "\3\54\1\0\1\54\10\0\32\54\22\0\1\54\1\55"+
    "\1\54\1\0\1\56\10\0\1\54\1\56\30\54\22\0"+
    "\1\54\1\126\1\54\1\0\1\54\1\127\7\0\32\54"+
    "\7\0\1\127\11\0\11\61\1\0\3\61\1\0\53\61"+
    "\12\62\1\130\56\62\15\63\1\0\53\63\1\0\3\3"+
    "\1\0\1\3\10\0\2\3\1\131\27\3\22\0\3\3"+
    "\1\0\1\3\10\0\1\3\1\132\30\3\22\0\3\3"+
    "\1\0\1\3\10\0\20\3\1\133\11\3\22\0\3\3"+
    "\1\0\1\3\10\0\17\3\1\134\12\3\22\0\3\3"+
    "\1\0\1\3\10\0\5\3\1\135\11\3\1\136\12\3"+
    "\22\0\3\3\1\0\1\3\10\0\21\3\1\137\10\3"+
    "\22\0\3\3\1\0\1\3\10\0\17\3\1\140\12\3"+
    "\22\0\3\3\1\0\1\3\10\0\6\3\1\141\23\3"+
    "\22\0\3\3\1\0\1\3\10\0\12\3\1\142\17\3"+
    "\22\0\3\3\1\0\1\3\10\0\13\3\1\143\16\3"+
    "\22\0\3\3\1\0\1\3\10\0\20\3\1\144\11\3"+
    "\22\0\3\3\1\0\1\3\10\0\15\3\1\145\14\3"+
    "\22\0\3\3\1\0\1\3\10\0\3\3\1\146\26\3"+
    "\22\0\3\3\1\0\1\3\10\0\1\147\31\3\22\0"+
    "\3\3\1\0\1\3\10\0\3\3\1\150\26\3\22\0"+
    "\3\3\1\0\1\3\10\0\4\3\1\151\25\3\22\0"+
    "\3\3\1\0\1\3\10\0\21\3\1\152\10\3\22\0"+
    "\3\3\1\0\1\3\10\0\10\3\1\153\21\3\22\0"+
    "\3\3\1\0\1\3\10\0\10\3\1\154\21\3\22\0"+
    "\3\3\1\0\1\3\10\0\10\3\1\155\6\3\1\156"+
    "\12\3\22\0\3\3\1\0\1\3\10\0\15\3\1\157"+
    "\14\3\22\0\3\3\1\0\1\3\10\0\3\3\1\160"+
    "\26\3\22\0\3\3\1\0\1\3\10\0\12\3\1\161"+
    "\17\3\22\0\3\3\1\0\1\3\10\0\1\3\1\162"+
    "\30\3\22\0\3\3\1\0\1\3\10\0\10\3\1\163"+
    "\21\3\22\0\3\3\1\0\1\3\10\0\3\3\1\164"+
    "\26\3\22\0\3\3\1\0\1\3\10\0\3\3\1\165"+
    "\26\3\22\0\3\3\1\0\1\3\10\0\15\3\1\166"+
    "\14\3\22\0\3\3\1\0\1\3\10\0\30\3\1\167"+
    "\1\3\22\0\1\54\1\126\1\54\1\0\1\54\10\0"+
    "\32\54\23\0\1\170\66\0\10\62\1\171\60\62\1\0"+
    "\3\3\1\0\1\3\10\0\3\3\1\172\26\3\22\0"+
    "\3\3\1\0\1\3\10\0\10\3\1\173\21\3\22\0"+
    "\3\3\1\0\1\3\10\0\13\3\1\174\16\3\22\0"+
    "\3\3\1\0\1\3\10\0\1\3\1\175\30\3\22\0"+
    "\3\3\1\0\1\3\10\0\3\3\1\176\16\3\1\177"+
    "\7\3\22\0\3\3\1\0\1\3\10\0\1\3\1\200"+
    "\30\3\22\0\3\3\1\0\1\3\10\0\1\3\1\201"+
    "\30\3\22\0\3\3\1\0\1\3\10\0\1\3\1\202"+
    "\30\3\22\0\3\3\1\0\1\3\10\0\10\3\1\203"+
    "\21\3\22\0\3\3\1\0\1\3\10\0\1\204\31\3"+
    "\22\0\3\3\1\0\1\3\10\0\21\3\1\161\10\3"+
    "\22\0\3\3\1\0\1\3\10\0\10\3\1\205\21\3"+
    "\22\0\3\3\1\0\1\3\10\0\4\3\1\206\25\3"+
    "\22\0\3\3\1\0\1\3\10\0\13\3\1\207\16\3"+
    "\22\0\3\3\1\0\1\3\10\0\4\3\1\210\11\3"+
    "\1\211\13\3\22\0\3\3\1\0\1\3\10\0\2\3"+
    "\1\175\27\3\22\0\3\3\1\0\1\3\10\0\1\3"+
    "\1\212\30\3\22\0\3\3\1\0\1\3\10\0\21\3"+
    "\1\213\10\3\22\0\3\3\1\0\1\3\10\0\15\3"+
    "\1\175\14\3\22\0\3\3\1\0\1\3\10\0\13\3"+
    "\1\175\16\3\22\0\3\3\1\0\1\3\10\0\12\3"+
    "\1\214\17\3\22\0\3\3\1\0\1\3\10\0\14\3"+
    "\1\215\15\3\22\0\3\3\1\0\1\3\10\0\5\3"+
    "\1\216\24\3\22\0\3\3\1\0\1\3\10\0\1\3"+
    "\1\217\30\3\22\0\3\3\1\0\1\3\10\0\4\3"+
    "\1\220\25\3\22\0\3\3\1\0\1\3\10\0\17\3"+
    "\1\221\12\3\22\0\3\3\1\0\1\3\10\0\17\3"+
    "\1\222\12\3\22\0\3\3\1\0\1\3\10\0\13\3"+
    "\1\223\16\3\22\0\3\3\1\0\1\3\10\0\3\3"+
    "\1\224\26\3\22\0\3\3\1\0\1\3\10\0\4\3"+
    "\1\225\25\3\22\0\3\3\1\0\1\3\10\0\24\3"+
    "\1\226\5\3\22\0\3\3\1\0\1\3\10\0\1\3"+
    "\1\227\30\3\22\0\3\3\1\0\1\3\10\0\6\3"+
    "\1\230\23\3\22\0\3\3\1\0\1\3\10\0\23\3"+
    "\1\231\6\3\22\0\3\3\1\0\1\3\10\0\15\3"+
    "\1\232\14\3\22\0\3\3\1\0\1\3\10\0\2\3"+
    "\1\233\27\3\22\0\3\3\1\0\1\3\10\0\12\3"+
    "\1\234\17\3\22\0\3\3\1\0\1\3\10\0\13\3"+
    "\1\134\16\3\22\0\3\3\1\0\1\3\10\0\17\3"+
    "\1\175\12\3\22\0\3\3\1\0\1\3\10\0\3\3"+
    "\1\235\26\3\22\0\3\3\1\0\1\3\10\0\17\3"+
    "\1\236\12\3\22\0\3\3\1\0\1\3\10\0\10\3"+
    "\1\237\21\3\22\0\3\3\1\0\1\3\10\0\21\3"+
    "\1\240\10\3\22\0\3\3\1\0\1\3\10\0\15\3"+
    "\1\241\14\3\22\0\3\3\1\0\1\3\10\0\23\3"+
    "\1\111\6\3\22\0\3\3\1\0\1\3\10\0\3\3"+
    "\1\242\26\3\22\0\3\3\1\0\1\3\10\0\14\3"+
    "\1\243\15\3\22\0\3\3\1\0\1\3\10\0\1\3"+
    "\1\244\30\3\22\0\3\3\1\0\1\3\10\0\4\3"+
    "\1\245\25\3\22\0\3\3\1\0\1\3\10\0\10\3"+
    "\1\246\21\3\22\0\3\3\1\0\1\3\10\0\3\3"+
    "\1\247\26\3\22\0\3\3\1\0\1\3\10\0\20\3"+
    "\1\175\11\3\22\0\3\3\1\0\1\3\10\0\1\3"+
    "\1\154\30\3\22\0\3\3\1\0\1\3\10\0\13\3"+
    "\1\250\16\3\22\0\3\3\1\0\1\3\10\0\14\3"+
    "\1\251\15\3\22\0\3\3\1\0\1\3\10\0\13\3"+
    "\1\252\16\3\22\0\3\3\1\0\1\3\10\0\17\3"+
    "\1\253\12\3\22\0\3\3\1\0\1\3\10\0\4\3"+
    "\1\254\25\3\22\0\3\3\1\0\1\3\10\0\14\3"+
    "\1\255\15\3\22\0\3\3\1\0\1\3\10\0\23\3"+
    "\1\256\6\3\22\0\3\3\1\0\1\3\10\0\2\3"+
    "\1\257\27\3\22\0\3\3\1\0\1\3\10\0\4\3"+
    "\1\175\25\3\22\0\3\3\1\0\1\3\10\0\13\3"+
    "\1\260\16\3\22\0\3\3\1\0\1\3\10\0\17\3"+
    "\1\261\12\3\22\0\3\3\1\0\1\3\10\0\4\3"+
    "\1\262\25\3\22\0\3\3\1\0\1\3\10\0\1\3"+
    "\1\263\30\3\22\0\3\3\1\0\1\3\10\0\1\3"+
    "\1\264\30\3\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7752];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\41\1\10\11\3\1\2\11\1\1\2\0"+
    "\1\11\1\0\36\1\2\11\1\1\2\0\40\1\1\11"+
    "\73\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 13: 
          { return symbol(sym.DosPuntos, yytext());
          }
        case 52: break;
        case 30: 
          { return symbol(sym.Int, yytext());
          }
        case 53: break;
        case 12: 
          { return symbol(sym.Igual, yytext());
          }
        case 54: break;
        case 2: 
          { if (yytext().length() > 10) {
        return symbol(sym.ERROR, yytext());
    }
    return symbol(sym.Identificador, yytext());
          }
        case 55: break;
        case 11: 
          { return symbol(sym.Op_relacional, yytext());
          }
        case 56: break;
        case 8: 
          { return symbol(sym.Multiplicacion, yytext());
          }
        case 57: break;
        case 51: 
          { return symbol(sym.EndWhile, yytext());
          }
        case 58: break;
        case 44: 
          { return symbol(sym.Return, yytext());
          }
        case 59: break;
        case 5: 
          { return symbol(sym.Resta, yytext());
          }
        case 60: break;
        case 3: 
          { return symbol(sym.Numero, yytext());
          }
        case 61: break;
        case 45: 
          { return symbol(sym.Static, yytext());
          }
        case 62: break;
        case 24: 
          { return symbol(sym.Op_atribucion, yytext());
          }
        case 63: break;
        case 39: 
          { return symbol(sym.Begin, yytext());
          }
        case 64: break;
        case 49: 
          { return symbol(sym.Println, yytext());
          }
        case 65: break;
        case 22: 
          { return symbol(sym.Coma, yytext());
          }
        case 66: break;
        case 29: 
          { return symbol(sym.End, yytext());
          }
        case 67: break;
        case 14: 
          { return symbol(sym.Suma, yytext());
          }
        case 68: break;
        case 6: 
          { /* Ignore */
          }
        case 69: break;
        case 18: 
          { return symbol(sym.Llave_c, yytext());
          }
        case 70: break;
        case 46: 
          { return symbol(sym.Switch, yytext());
          }
        case 71: break;
        case 15: 
          { return symbol(sym.Parentesis_a, yytext());
          }
        case 72: break;
        case 19: 
          { return symbol(sym.Corchete_a, yytext());
          }
        case 73: break;
        case 7: 
          { return symbol(sym.Division, yytext());
          }
        case 74: break;
        case 31: 
          { return symbol(sym.For, yytext());
          }
        case 75: break;
        case 26: 
          { return symbol(sym.In, yytext());
          }
        case 76: break;
        case 9: 
          { return symbol(sym.Comillas, yytext());
          }
        case 77: break;
        case 34: 
          { return symbol(sym.Main, yytext());
          }
        case 78: break;
        case 37: 
          { return symbol(sym.Op_booleano, yytext());
          }
        case 79: break;
        case 28: 
          { return symbol(sym.Do, yytext());
          }
        case 80: break;
        case 40: 
          { return symbol(sym.Break, yytext());
          }
        case 81: break;
        case 33: 
          { return symbol(sym.Else, yytext());
          }
        case 82: break;
        case 48: 
          { return symbol(sym.Default, yytext());
          }
        case 83: break;
        case 38: 
          { return symbol(sym.Then, yytext());
          }
        case 84: break;
        case 23: 
          { return symbol(sym.Op_incremento, yytext());
          }
        case 85: break;
        case 25: 
          { return symbol(sym.Cadena, yytext().substring(1, yytext().length()-1));
          }
        case 86: break;
        case 4: 
          { return symbol(sym.Punto, yytext());
          }
        case 87: break;
        case 47: 
          { return symbol(sym.String_type, yytext());
          }
        case 88: break;
        case 21: 
          { return symbol(sym.P_coma, yytext());
          }
        case 89: break;
        case 36: 
          { return symbol(sym.Void, yytext());
          }
        case 90: break;
        case 43: 
          { return symbol(sym.Public, yytext());
          }
        case 91: break;
        case 42: 
          { return symbol(sym.While, yytext());
          }
        case 92: break;
        case 16: 
          { return symbol(sym.Parentesis_c, yytext());
          }
        case 93: break;
        case 32: 
          { return symbol(sym.T_dato, yytext());
          }
        case 94: break;
        case 20: 
          { return symbol(sym.Corchete_c, yytext());
          }
        case 95: break;
        case 50: 
          { return symbol(sym.Private, yytext());
          }
        case 96: break;
        case 27: 
          { return symbol(sym.If, yytext());
          }
        case 97: break;
        case 41: 
          { return symbol(sym.Class, yytext());
          }
        case 98: break;
        case 35: 
          { return symbol(sym.Case, yytext());
          }
        case 99: break;
        case 10: 
          { return symbol(sym.Op_logico, yytext());
          }
        case 100: break;
        case 1: 
          { return symbol(sym.ERROR, yytext());
          }
        case 101: break;
        case 17: 
          { return symbol(sym.Llave_a, yytext());
          }
        case 102: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
