/* The following code was generated by JFlex 1.4.1 on 28/02/26, 7:21 p.m. */

package proyectofinalcompilador.Lexico;
import java_cup.runtime.Symbol;
import proyectofinalcompilador.Sintactico.sym;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 28/02/26, 7:21 p.m. from the specification file
 * <tt>src/proyectofinalcompilador/Lexico/LexerCup.flex</tt>
 */
public class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  5,  0,  0,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3, 34,  6,  0,  0, 37, 32,  0, 38, 39, 31, 29,  0, 30, 46,  4, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 45, 45, 36, 28, 35,  0, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1, 26,  1,  1,  1,  1,  1,  1,  1, 42,  0, 43,  0,  1, 
     0, 13,  7, 11, 20, 10, 19, 18, 12, 22,  1,  1, 15, 44, 17, 16, 
    23,  1, 14, 24,  9, 21, 25, 27,  1,  8,  1, 40, 33, 41,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\15\2"+
    "\1\7\1\10\1\11\1\12\3\13\2\14\1\1\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\2\1\23\1\24"+
    "\1\4\1\25\1\0\1\26\11\2\1\27\1\2\1\30"+
    "\5\2\1\14\1\31\1\13\1\0\11\2\1\32\1\2"+
    "\1\33\5\2\1\0\1\2\1\34\1\35\1\36\5\2"+
    "\1\37\2\2\1\3\1\40\1\41\3\2\1\42\1\43"+
    "\1\44\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439"+
    "\0\u0468\0\u0497\0\u03ac\0\u04c6\0\u04f5\0\u0439\0\u0524\0\57"+
    "\0\57\0\57\0\57\0\57\0\u0553\0\57\0\57\0\u0582"+
    "\0\57\0\u011a\0\57\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\136\0\u07b6"+
    "\0\u07e5\0\u0814\0\u0843\0\u0872\0\57\0\57\0\57\0\u08a1"+
    "\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19"+
    "\0\u0a48\0\136\0\u0a77\0\136\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33"+
    "\0\u0b62\0\u0b91\0\u0bc0\0\136\0\136\0\136\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u0c7c\0\u0cab\0\136\0\u0cda\0\u0d09\0\57\0\136"+
    "\0\136\0\u0d38\0\u0d67\0\u0d96\0\136\0\136\0\136\0\136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\3\1\11\1\12\1\13\3\3\1\14\3\3\1\15"+
    "\1\16\1\3\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\60\0\2\3\4\0\25\3\20\0"+
    "\1\3\4\0\1\4\57\0\1\5\1\0\1\5\55\0"+
    "\1\50\27\0\1\51\22\0\6\52\1\53\50\52\1\0"+
    "\2\3\4\0\1\3\1\54\23\3\20\0\1\3\3\0"+
    "\2\3\4\0\7\3\1\55\15\3\20\0\1\3\3\0"+
    "\2\3\4\0\10\3\1\56\14\3\20\0\1\3\3\0"+
    "\2\3\4\0\5\3\1\57\2\3\1\60\14\3\20\0"+
    "\1\3\3\0\2\3\4\0\11\3\1\61\13\3\20\0"+
    "\1\3\3\0\2\3\4\0\6\3\1\62\1\3\1\63"+
    "\1\64\13\3\20\0\1\3\3\0\2\3\4\0\11\3"+
    "\1\65\13\3\20\0\1\3\3\0\2\3\4\0\12\3"+
    "\1\66\1\3\1\67\10\3\20\0\1\3\3\0\2\3"+
    "\4\0\16\3\1\70\6\3\20\0\1\3\3\0\2\3"+
    "\4\0\2\3\1\71\22\3\20\0\1\3\3\0\2\3"+
    "\4\0\11\3\1\72\13\3\20\0\1\3\3\0\2\3"+
    "\4\0\2\3\1\73\22\3\20\0\1\3\3\0\2\3"+
    "\4\0\5\3\1\74\17\3\20\0\1\3\36\0\1\75"+
    "\56\0\1\51\1\76\55\0\1\51\1\0\1\76\54\0"+
    "\1\51\62\0\1\77\57\0\1\77\51\0\1\75\6\0"+
    "\1\75\47\0\1\75\7\0\1\75\50\0\1\100\21\0"+
    "\2\3\4\0\6\3\1\101\16\3\20\0\1\3\2\0"+
    "\5\50\1\0\51\50\1\0\2\3\4\0\2\3\1\102"+
    "\22\3\20\0\1\3\3\0\2\3\4\0\16\3\1\103"+
    "\6\3\20\0\1\3\3\0\2\3\4\0\21\3\1\104"+
    "\3\3\20\0\1\3\3\0\2\3\4\0\6\3\1\105"+
    "\16\3\20\0\1\3\3\0\2\3\4\0\6\3\1\106"+
    "\16\3\20\0\1\3\3\0\2\3\4\0\12\3\1\107"+
    "\12\3\20\0\1\3\3\0\2\3\4\0\10\3\1\110"+
    "\14\3\20\0\1\3\3\0\2\3\4\0\11\3\1\111"+
    "\13\3\20\0\1\3\3\0\2\3\4\0\7\3\1\112"+
    "\15\3\20\0\1\3\3\0\2\3\4\0\16\3\1\113"+
    "\6\3\20\0\1\3\3\0\2\3\4\0\2\3\1\114"+
    "\22\3\20\0\1\3\3\0\2\3\4\0\1\115\24\3"+
    "\20\0\1\3\3\0\2\3\4\0\6\3\1\116\16\3"+
    "\20\0\1\3\3\0\2\3\4\0\17\3\1\117\5\3"+
    "\20\0\1\3\3\0\2\3\4\0\7\3\1\120\15\3"+
    "\20\0\1\3\3\0\2\3\4\0\17\3\1\121\5\3"+
    "\20\0\1\3\4\0\1\122\55\0\2\3\4\0\17\3"+
    "\1\123\5\3\20\0\1\3\3\0\2\3\4\0\3\3"+
    "\1\124\21\3\20\0\1\3\3\0\2\3\4\0\3\3"+
    "\1\125\21\3\20\0\1\3\3\0\2\3\4\0\3\3"+
    "\1\126\21\3\20\0\1\3\3\0\2\3\4\0\7\3"+
    "\1\124\15\3\20\0\1\3\3\0\2\3\4\0\21\3"+
    "\1\127\3\3\20\0\1\3\3\0\2\3\4\0\13\3"+
    "\1\124\11\3\20\0\1\3\3\0\2\3\4\0\21\3"+
    "\1\103\3\3\20\0\1\3\3\0\2\3\4\0\6\3"+
    "\1\130\16\3\20\0\1\3\3\0\2\3\4\0\1\131"+
    "\24\3\20\0\1\3\3\0\2\3\4\0\10\3\1\132"+
    "\14\3\20\0\1\3\3\0\2\3\4\0\2\3\1\133"+
    "\22\3\20\0\1\3\3\0\2\3\4\0\15\3\1\134"+
    "\7\3\20\0\1\3\3\0\2\3\4\0\17\3\1\135"+
    "\5\3\20\0\1\3\3\0\2\3\4\0\10\3\1\136"+
    "\14\3\20\0\1\3\4\0\1\122\44\0\1\137\10\0"+
    "\2\3\4\0\12\3\1\140\12\3\20\0\1\3\3\0"+
    "\2\3\4\0\21\3\1\141\3\3\20\0\1\3\3\0"+
    "\2\3\4\0\2\3\1\124\22\3\20\0\1\3\3\0"+
    "\2\3\4\0\10\3\1\102\14\3\20\0\1\3\3\0"+
    "\2\3\4\0\17\3\1\142\5\3\20\0\1\3\3\0"+
    "\2\3\4\0\17\3\1\143\5\3\20\0\1\3\3\0"+
    "\2\3\4\0\12\3\1\144\12\3\20\0\1\3\3\0"+
    "\2\3\4\0\3\3\1\145\21\3\20\0\1\3\3\0"+
    "\2\3\4\0\4\3\1\146\20\3\20\0\1\3\3\0"+
    "\2\3\4\0\4\3\1\147\20\3\20\0\1\3\3\0"+
    "\2\3\4\0\13\3\1\150\11\3\20\0\1\3\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3525];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\35\1\5\11\1\1\2\11\1\1\1\11"+
    "\1\0\1\11\21\1\3\11\1\0\21\1\1\0\14\1"+
    "\1\11\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 27: 
          { return symbol(sym.Int, yytext());
          }
        case 38: break;
        case 7: 
          { return symbol(sym.Igual, yytext());
          }
        case 39: break;
        case 12: 
          { return symbol(sym.Op_relacional, yytext());
          }
        case 40: break;
        case 10: 
          { return symbol(sym.Multiplicacion, yytext());
          }
        case 41: break;
        case 9: 
          { return symbol(sym.Resta, yytext());
          }
        case 42: break;
        case 3: 
          { return symbol(sym.Numero, yytext());
          }
        case 43: break;
        case 36: 
          { return symbol(sym.Static, yytext());
          }
        case 44: break;
        case 21: 
          { return symbol(sym.Op_atribucion, yytext());
          }
        case 45: break;
        case 8: 
          { return symbol(sym.Suma, yytext());
          }
        case 46: break;
        case 2: 
          { return symbol(sym.Identificador, yytext());
          }
        case 47: break;
        case 16: 
          { return symbol(sym.Llave_c, yytext());
          }
        case 48: break;
        case 13: 
          { return symbol(sym.Parentesis_a, yytext());
          }
        case 49: break;
        case 17: 
          { return symbol(sym.Corchete_a, yytext());
          }
        case 50: break;
        case 5: 
          { return symbol(sym.Division, yytext());
          }
        case 51: break;
        case 26: 
          { return symbol(sym.For, yytext());
          }
        case 52: break;
        case 6: 
          { return symbol(sym.Comillas, yytext());
          }
        case 53: break;
        case 32: 
          { return symbol(sym.Main, yytext());
          }
        case 54: break;
        case 29: 
          { return symbol(sym.Op_booleano, yytext());
          }
        case 55: break;
        case 23: 
          { return symbol(sym.Do, yytext());
          }
        case 56: break;
        case 30: 
          { return symbol(sym.Else, yytext());
          }
        case 57: break;
        case 25: 
          { return symbol(sym.Op_incremento, yytext());
          }
        case 58: break;
        case 22: 
          { return symbol(sym.Cadena, yytext().substring(1, yytext().length()-1));
          }
        case 59: break;
        case 20: 
          { return symbol(sym.Punto, yytext());
          }
        case 60: break;
        case 37: 
          { return symbol(sym.String_type, yytext());
          }
        case 61: break;
        case 19: 
          { return symbol(sym.P_coma, yytext());
          }
        case 62: break;
        case 31: 
          { return symbol(sym.Void, yytext());
          }
        case 63: break;
        case 35: 
          { return symbol(sym.Public, yytext());
          }
        case 64: break;
        case 14: 
          { return symbol(sym.Parentesis_c, yytext());
          }
        case 65: break;
        case 34: 
          { return symbol(sym.While, yytext());
          }
        case 66: break;
        case 28: 
          { return symbol(sym.T_dato, yytext());
          }
        case 67: break;
        case 18: 
          { return symbol(sym.Corchete_c, yytext());
          }
        case 68: break;
        case 4: 
          { /*Ignore*/
          }
        case 69: break;
        case 24: 
          { return symbol(sym.If, yytext());
          }
        case 70: break;
        case 33: 
          { return symbol(sym.Class, yytext());
          }
        case 71: break;
        case 11: 
          { return symbol(sym.Op_logico, yytext());
          }
        case 72: break;
        case 1: 
          { return symbol(sym.ERROR, yytext());
          }
        case 73: break;
        case 15: 
          { return symbol(sym.Llave_a, yytext());
          }
        case 74: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
