
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectofinalcompilador.Sintactico;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class sintax extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public sintax() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\042\000\002\002\004\000\002\002\003\000\002\003" +
    "\003\000\002\004\010\000\002\004\007\000\002\005\014" +
    "\000\002\005\013\000\002\005\012\000\002\006\006\000" +
    "\002\006\006\000\002\006\004\000\002\006\004\000\002" +
    "\011\004\000\002\011\003\000\002\007\004\000\002\007" +
    "\004\000\002\007\013\000\002\012\004\000\002\012\006" +
    "\000\002\012\006\000\002\012\004\000\002\013\005\000" +
    "\002\013\005\000\002\013\003\000\002\014\005\000\002" +
    "\014\005\000\002\014\003\000\002\015\003\000\002\015" +
    "\003\000\002\015\005\000\002\010\003\000\002\010\005" +
    "\000\002\010\003\000\002\010\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\130\000\006\034\005\035\004\001\002\000\004\043" +
    "\127\001\002\000\004\035\012\001\002\000\004\002\011" +
    "\001\002\000\004\002\000\001\002\000\004\002\uffff\001" +
    "\002\000\004\002\001\001\002\000\004\043\013\001\002" +
    "\000\004\024\014\001\002\000\006\034\017\037\015\001" +
    "\002\000\004\030\120\001\002\000\004\025\117\001\002" +
    "\000\004\036\020\001\002\000\004\037\021\001\002\000" +
    "\004\030\022\001\002\000\004\022\023\001\002\000\010" +
    "\023\027\040\024\043\026\001\002\000\006\026\111\043" +
    "\112\001\002\000\004\023\105\001\002\000\004\043\104" +
    "\001\002\000\004\024\030\001\002\000\010\006\036\042" +
    "\035\043\034\001\002\000\004\031\103\001\002\000\012" +
    "\006\036\025\101\042\035\043\034\001\002\000\012\006" +
    "\ufff4\025\ufff4\042\ufff4\043\ufff4\001\002\000\006\031\064" +
    "\033\065\001\002\000\004\043\061\001\002\000\004\043" +
    "\037\001\002\000\006\014\040\031\ufff0\001\002\000\010" +
    "\022\043\041\041\043\046\001\002\000\016\015\uffe6\016" +
    "\uffe6\017\uffe6\020\uffe6\023\uffe6\031\uffe6\001\002\000\016" +
    "\015\uffe7\016\uffe7\017\uffe7\020\uffe7\023\uffe7\031\uffe7\001" +
    "\002\000\010\022\043\041\041\043\046\001\002\000\016" +
    "\015\uffea\016\uffea\017\053\020\052\023\uffea\031\uffea\001" +
    "\002\000\010\015\050\016\047\031\uffef\001\002\000\016" +
    "\015\uffe5\016\uffe5\017\uffe5\020\uffe5\023\uffe5\031\uffe5\001" +
    "\002\000\010\022\043\041\041\043\046\001\002\000\010" +
    "\022\043\041\041\043\046\001\002\000\016\015\uffec\016" +
    "\uffec\017\053\020\052\023\uffec\031\uffec\001\002\000\010" +
    "\022\043\041\041\043\046\001\002\000\010\022\043\041" +
    "\041\043\046\001\002\000\016\015\uffe9\016\uffe9\017\uffe9" +
    "\020\uffe9\023\uffe9\031\uffe9\001\002\000\016\015\uffe8\016" +
    "\uffe8\017\uffe8\020\uffe8\023\uffe8\031\uffe8\001\002\000\016" +
    "\015\uffeb\016\uffeb\017\053\020\052\023\uffeb\031\uffeb\001" +
    "\002\000\010\015\050\016\047\023\060\001\002\000\016" +
    "\015\uffe4\016\uffe4\017\uffe4\020\uffe4\023\uffe4\031\uffe4\001" +
    "\002\000\006\014\062\031\uffed\001\002\000\010\022\043" +
    "\041\041\043\046\001\002\000\010\015\050\016\047\031" +
    "\uffee\001\002\000\012\006\ufff2\025\ufff2\042\ufff2\043\ufff2" +
    "\001\002\000\004\043\066\001\002\000\004\033\067\001" +
    "\002\000\004\043\070\001\002\000\004\022\071\001\002" +
    "\000\014\022\043\023\uffe0\041\041\043\046\050\074\001" +
    "\002\000\010\015\050\016\047\023\uffe1\001\002\000\004" +
    "\023\077\001\002\000\006\015\075\023\uffe3\001\002\000" +
    "\010\022\043\041\041\043\046\001\002\000\010\015\050" +
    "\016\047\023\uffe2\001\002\000\004\031\100\001\002\000" +
    "\012\006\ufff1\025\ufff1\042\ufff1\043\ufff1\001\002\000\004" +
    "\025\ufffb\001\002\000\012\006\ufff5\025\ufff5\042\ufff5\043" +
    "\ufff5\001\002\000\012\006\ufff3\025\ufff3\042\ufff3\043\ufff3" +
    "\001\002\000\004\023\ufff6\001\002\000\004\024\106\001" +
    "\002\000\010\006\036\042\035\043\034\001\002\000\012" +
    "\006\036\025\110\042\035\043\034\001\002\000\004\025" +
    "\ufffc\001\002\000\004\027\115\001\002\000\006\023\ufff7" +
    "\026\113\001\002\000\004\027\114\001\002\000\004\023" +
    "\ufff8\001\002\000\004\043\116\001\002\000\004\023\ufff9" +
    "\001\002\000\004\002\ufffe\001\002\000\004\022\121\001" +
    "\002\000\006\040\024\043\026\001\002\000\004\023\123" +
    "\001\002\000\004\024\124\001\002\000\010\006\036\042" +
    "\035\043\034\001\002\000\012\006\036\025\126\042\035" +
    "\043\034\001\002\000\004\025\ufffa\001\002\000\004\024" +
    "\130\001\002\000\006\034\017\037\015\001\002\000\004" +
    "\025\132\001\002\000\004\002\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\130\000\010\002\005\003\006\004\007\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\015\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\024" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\007\032\011\031\012\030" +
    "\001\001\000\002\001\001\000\006\007\101\012\030\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\013\044\014" +
    "\043\015\041\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\013\056\014\043\015\041\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\014\055" +
    "\015\041\001\001\000\006\014\050\015\041\001\001\000" +
    "\002\001\001\000\004\015\054\001\001\000\004\015\053" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\013\062\014\043\015\041\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\010\072\013" +
    "\071\014\043\015\041\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\013\075\014\043\015" +
    "\041\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\007\032" +
    "\011\106\012\030\001\001\000\006\007\101\012\030\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\006\121\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\032\011\124\012\030\001\001\000\006\007\101" +
    "\012\030\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\130\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private java_cup.runtime.Symbol s;
    private boolean errorEncontrado = false;
    private Object resultado = null;
    private proyectofinalcompilador.Semantico.TablaSimbolos tabla = new proyectofinalcompilador.Semantico.TablaSimbolos();
    private proyectofinalcompilador.CodigoIntermedio.GeneradorIntermedio genInter = new proyectofinalcompilador.CodigoIntermedio.GeneradorIntermedio();

    public void syntax_error(java_cup.runtime.Symbol s){
        this.s = s;
        this.errorEncontrado = true;
    }

    public void unrecovered_syntax_error(java_cup.runtime.Symbol s) throws java.lang.Exception {
        this.s = s;
        this.errorEncontrado = true;
    }

    public java_cup.runtime.Symbol getS(){
        return this.s;
    }

    public boolean hayError(){
        return this.errorEncontrado;
    }

    public void resetError(){
        this.s = null;
        this.errorEncontrado = false;
        this.resultado = null;
        this.tabla.limpiar();
        this.genInter.limpiar();
    }

    public void setResultado(Object r){
        this.resultado = r;
    }

    public Object getResultado(){
        return this.resultado;
    }

    public proyectofinalcompilador.Semantico.TablaSimbolos getTabla() {
        return this.tabla;
    }

    public proyectofinalcompilador.CodigoIntermedio.GeneradorIntermedio getGenInter() {
        return this.genInter;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$sintax$actions {
  private final sintax parser;

  /** Constructor */
  CUP$sintax$actions(sintax parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$sintax$do_action_part00000000(
    int                        CUP$sintax$act_num,
    java_cup.runtime.lr_parser CUP$sintax$parser,
    java.util.Stack            CUP$sintax$stack,
    int                        CUP$sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$sintax$result;

      /* select the action based on the action number */
      switch (CUP$sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		RESULT = start_val;
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$sintax$parser.done_parsing();
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= PROGRAMA 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = p; parser.setResultado(p); 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROGRAMA ::= CLASE 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = "Arbol Sintáctico:\n" + c; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PROGRAMA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // CLASE ::= Public Class Identificador Llave_a METODO Llave_c 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String m = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 
        RESULT = "└── Clase: " + id + "\n    " + m.replace("\n", "\n    "); 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CLASE",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CLASE ::= Class Identificador Llave_a METODO Llave_c 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String m = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 
        RESULT = "└── Clase: " + id + "\n    " + m.replace("\n", "\n    "); 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CLASE",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // METODO ::= Public Static Void Main Parentesis_a PARAMETROS Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 
        RESULT = "└── Método: main(" + p + ")\n    └── Cuerpo:\n        " + s.replace("\n", "\n        "); 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("METODO",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-9)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // METODO ::= Public Static Void Main Parentesis_a Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 
        RESULT = "└── Método: main()\n    └── Cuerpo:\n        " + s.replace("\n", "\n        "); 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("METODO",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-8)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // METODO ::= Void Main Parentesis_a PARAMETROS Parentesis_c Llave_a LISTA_SENTENCIAS Llave_c 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 
        RESULT = "└── Método: main(" + p + ")\n    └── Cuerpo:\n        " + s.replace("\n", "\n        "); 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("METODO",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-7)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // PARAMETROS ::= String_type Corchete_a Corchete_c Identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "String[]", "null", "local", idleft + 1));
        RESULT = "String[] " + id; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS",4, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // PARAMETROS ::= String_type Identificador Corchete_a Corchete_c 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		 
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "String[]", "null", "local", idleft + 1));
        RESULT = "String " + id + "[]"; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS",4, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // PARAMETROS ::= String_type Identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "String", "null", "local", idleft + 1));
        RESULT = "String " + id; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS",4, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // PARAMETROS ::= Identificador Identificador 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, t, "null", "local", idleft + 1));
        RESULT = t + " " + id; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS",4, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // LISTA_SENTENCIAS ::= LISTA_SENTENCIAS SENTENCIA 
            {
              String RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String ls = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = ls + "\n" + s; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",7, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // LISTA_SENTENCIAS ::= SENTENCIA 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = s; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",7, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= DECLARACION P_coma 
            {
              String RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 RESULT = d; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",5, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTENCIA ::= Identificador P_coma 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 
        parser.getTabla().verificarExistencia(id, idleft + 1);
        RESULT = "└── Sentencia: " + id; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",5, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SENTENCIA ::= Identificador Punto Identificador Punto Identificador Parentesis_a CONTENIDO_PARENTESIS Parentesis_c P_coma 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-8)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-8)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-8)).value;
		int p1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)).left;
		int p1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)).right;
		String p1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-6)).value;
		int p2left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int p2right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String p2 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int cpleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int cpright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String cp = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        String cpVal = cp;
        if (cp.contains("::::")) cpVal = cp.split("::::")[1];
        parser.getGenInter().agregarLlamada(id + "." + p1 + "." + p2, cpVal);
        RESULT = "└── Llamada: " + id + "." + p1 + "." + p2 + "(" + (cp.contains("::::") ? cp.split("::::")[0] : cp) + ")";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",5, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-8)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // DECLARACION ::= Int Identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "int", "0", "local", idleft + 1));
        parser.getGenInter().agregarAsignacion(id, "0");
        RESULT = "└── Declaración: int " + id; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",8, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // DECLARACION ::= Int Identificador Igual EXPRESION 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        String[] parts = e.split("::::");
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "int", parts[0], "local", idleft + 1));
        parser.getGenInter().agregarAsignacion(id, parts[1]);
        RESULT = "└── Declaración: int " + id + " = " + parts[0]; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",8, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARACION ::= T_dato Identificador Igual EXPRESION 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        String[] parts = e.split("::::");
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, t, parts[0], "local", idleft + 1));
        parser.getGenInter().agregarAsignacion(id, parts[1]);
        RESULT = "└── Declaración: " + t + " " + id + " = " + parts[0]; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",8, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARACION ::= T_dato Identificador 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, t, "null", "local", idleft + 1));
        RESULT = "└── Declaración: " + t + " " + id; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",8, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EXPRESION ::= EXPRESION Suma TERMINO 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        String[] p1 = e1.split("::::");
        String[] p2 = t1.split("::::");
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, p1[1], "+", p2[1]);
        RESULT = p1[0] + " + " + p2[0] + "::::" + temp; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // EXPRESION ::= EXPRESION Resta TERMINO 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        String[] p1 = e1.split("::::");
        String[] p2 = t1.split("::::");
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, p1[1], "-", p2[1]);
        RESULT = p1[0] + " - " + p2[0] + "::::" + temp; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // EXPRESION ::= TERMINO 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = t1; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // TERMINO ::= TERMINO Multiplicacion FACTOR 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int f1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String f1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        String[] p1 = t1.split("::::");
        String[] p2 = f1.split("::::");
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, p1[1], "*", p2[1]);
        RESULT = p1[0] + " * " + p2[0] + "::::" + temp; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // TERMINO ::= TERMINO Division FACTOR 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int f1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String f1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        String[] p1 = t1.split("::::");
        String[] p2 = f1.split("::::");
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, p1[1], "/", p2[1]);
        RESULT = p1[0] + " / " + p2[0] + "::::" + temp; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // TERMINO ::= FACTOR 
            {
              String RESULT =null;
		int f1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String f1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = f1; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // FACTOR ::= Numero 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = n + "::::" + n; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // FACTOR ::= Identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        parser.getTabla().verificarExistencia(id, idleft + 1);
        RESULT = id + "::::" + id; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // FACTOR ::= Parentesis_a EXPRESION Parentesis_c 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 
        String[] p = e.split("::::");
        RESULT = "(" + p[0] + ")::::" + p[1]; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // CONTENIDO_PARENTESIS ::= Cadena 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = "\"" + c + "\"::::\"" + c + "\""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONTENIDO_PARENTESIS",6, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // CONTENIDO_PARENTESIS ::= Cadena Suma EXPRESION 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 
        String[] p = e.split("::::");
        RESULT = "\"" + c + "\" + " + p[0] + "::::\"" + c + "\" + " + p[1]; 
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONTENIDO_PARENTESIS",6, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // CONTENIDO_PARENTESIS ::= EXPRESION 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = e; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONTENIDO_PARENTESIS",6, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // CONTENIDO_PARENTESIS ::= 
            {
              String RESULT =null;
		 RESULT = ""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONTENIDO_PARENTESIS",6, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$sintax$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$sintax$do_action(
    int                        CUP$sintax$act_num,
    java_cup.runtime.lr_parser CUP$sintax$parser,
    java.util.Stack            CUP$sintax$stack,
    int                        CUP$sintax$top)
    throws java.lang.Exception
    {
              return CUP$sintax$do_action_part00000000(
                               CUP$sintax$act_num,
                               CUP$sintax$parser,
                               CUP$sintax$stack,
                               CUP$sintax$top);
    }
}

}
