
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectofinalcompilador.Sintactico;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class sintax extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public sintax() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\070\000\002\002\004\000\002\002\011\000\002\002" +
    "\010\000\002\002\003\000\002\003\004\000\002\003\003" +
    "\000\002\003\004\000\002\003\003\000\002\003\004\000" +
    "\002\003\003\000\002\003\004\000\002\003\003\000\002" +
    "\003\004\000\002\003\003\000\002\003\004\000\002\003" +
    "\003\000\002\004\005\000\002\004\007\000\002\004\007" +
    "\000\002\004\006\000\002\004\006\000\002\004\005\000" +
    "\002\004\007\000\002\004\007\000\002\004\006\000\002" +
    "\004\006\000\002\004\010\000\002\004\010\000\002\004" +
    "\011\000\002\004\011\000\002\006\011\000\002\013\003" +
    "\000\002\013\005\000\002\013\005\000\002\013\005\000" +
    "\002\013\006\000\002\013\007\000\002\007\015\000\002" +
    "\010\011\000\002\011\013\000\002\012\011\000\002\014" +
    "\012\000\002\014\011\000\002\005\005\000\002\005\004" +
    "\000\002\005\004\000\002\015\005\000\002\015\005\000" +
    "\002\015\003\000\002\016\005\000\002\016\005\000\002" +
    "\016\003\000\002\016\004\000\002\017\003\000\002\017" +
    "\003\000\002\020\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\232\000\012\007\007\030\006\036\010\042\013\001" +
    "\002\000\004\002\234\001\002\000\020\002\uffce\017\uffce" +
    "\020\uffce\021\uffce\022\uffce\030\uffce\031\uffce\001\002\000" +
    "\006\030\006\042\013\001\002\000\004\036\224\001\002" +
    "\000\004\030\026\001\002\000\020\002\uffd1\017\uffd1\020" +
    "\uffd1\021\022\022\021\030\006\031\uffd1\001\002\000\020" +
    "\002\uffcb\017\uffcb\020\uffcb\021\uffcb\022\uffcb\030\uffcb\031" +
    "\uffcb\001\002\000\020\002\uffcc\017\uffcc\020\uffcc\021\uffcc" +
    "\022\uffcc\030\uffcc\031\uffcc\001\002\000\010\002\ufffe\017" +
    "\016\020\015\001\002\000\006\030\006\042\013\001\002" +
    "\000\006\030\006\042\013\001\002\000\020\002\uffd3\017" +
    "\uffd3\020\uffd3\021\022\022\021\030\006\031\uffd3\001\002" +
    "\000\020\002\uffcd\017\uffcd\020\uffcd\021\uffcd\022\uffcd\030" +
    "\uffcd\031\uffcd\001\002\000\006\030\006\042\013\001\002" +
    "\000\006\030\006\042\013\001\002\000\020\002\uffd0\017" +
    "\uffd0\020\uffd0\021\uffd0\022\uffd0\030\uffd0\031\uffd0\001\002" +
    "\000\020\002\uffcf\017\uffcf\020\uffcf\021\uffcf\022\uffcf\030" +
    "\uffcf\031\uffcf\001\002\000\020\002\uffd2\017\uffd2\020\uffd2" +
    "\021\022\022\021\030\006\031\uffd2\001\002\000\004\031" +
    "\027\001\002\000\004\032\030\001\002\000\020\006\037" +
    "\007\043\010\036\011\033\013\040\014\032\015\045\001" +
    "\002\000\022\006\ufff6\007\ufff6\010\ufff6\011\ufff6\013\ufff6" +
    "\014\ufff6\015\ufff6\033\ufff6\001\002\000\004\030\216\001" +
    "\002\000\004\030\204\001\002\000\022\006\ufff2\007\ufff2" +
    "\010\ufff2\011\ufff2\013\ufff2\014\ufff2\015\ufff2\033\ufff2\001" +
    "\002\000\022\006\ufffc\007\ufffc\010\ufffc\011\ufffc\013\ufffc" +
    "\014\ufffc\015\ufffc\033\ufffc\001\002\000\004\040\165\001" +
    "\002\000\006\026\150\040\151\001\002\000\004\032\140" +
    "\001\002\000\022\006\ufff8\007\ufff8\010\ufff8\011\ufff8\013" +
    "\ufff8\014\ufff8\015\ufff8\033\ufff8\001\002\000\022\006\ufffa" +
    "\007\ufffa\010\ufffa\011\ufffa\013\ufffa\014\ufffa\015\ufffa\033" +
    "\ufffa\001\002\000\006\026\123\040\124\001\002\000\022" +
    "\006\037\007\043\010\036\011\033\013\040\014\032\015" +
    "\045\033\122\001\002\000\004\030\047\001\002\000\022" +
    "\006\ufff4\007\ufff4\010\ufff4\011\ufff4\013\ufff4\014\ufff4\015" +
    "\ufff4\033\ufff4\001\002\000\006\006\052\040\051\001\002" +
    "\000\004\031\110\001\002\000\004\016\102\001\002\000" +
    "\004\040\053\001\002\000\004\016\054\001\002\000\004" +
    "\042\055\001\002\000\004\037\056\001\002\000\006\027" +
    "\060\040\061\001\002\000\004\037\072\001\002\000\006" +
    "\031\uffe2\037\uffe2\001\002\000\004\024\062\001\002\000" +
    "\012\005\064\027\065\040\066\042\063\001\002\000\006" +
    "\031\uffe0\037\uffe0\001\002\000\006\005\067\040\070\001" +
    "\002\000\006\031\uffe1\037\uffe1\001\002\000\006\031\uffdf" +
    "\037\uffdf\001\002\000\006\031\uffde\037\uffde\001\002\000" +
    "\004\005\071\001\002\000\006\031\uffdd\037\uffdd\001\002" +
    "\000\006\026\074\040\075\001\002\000\004\031\uffd8\001" +
    "\002\000\004\040\101\001\002\000\006\025\076\026\077" +
    "\001\002\000\004\042\100\001\002\000\004\031\uffd5\001" +
    "\002\000\004\031\uffd6\001\002\000\004\031\uffd4\001\002" +
    "\000\004\042\103\001\002\000\004\037\104\001\002\000" +
    "\006\027\060\040\061\001\002\000\004\037\106\001\002" +
    "\000\006\026\074\040\075\001\002\000\004\031\uffd7\001" +
    "\002\000\004\032\111\001\002\000\020\006\037\007\043" +
    "\010\036\011\033\013\040\014\032\015\045\001\002\000" +
    "\022\006\037\007\043\010\036\011\033\013\040\014\032" +
    "\015\045\033\120\001\002\000\022\006\ufff7\007\ufff7\010" +
    "\ufff7\011\ufff7\013\ufff7\014\ufff7\015\ufff7\033\ufff7\001\002" +
    "\000\022\006\ufff3\007\ufff3\010\ufff3\011\ufff3\013\ufff3\014" +
    "\ufff3\015\ufff3\033\ufff3\001\002\000\022\006\ufffd\007\ufffd" +
    "\010\ufffd\011\ufffd\013\ufffd\014\ufffd\015\ufffd\033\ufffd\001" +
    "\002\000\022\006\ufff9\007\ufff9\010\ufff9\011\ufff9\013\ufff9" +
    "\014\ufff9\015\ufff9\033\ufff9\001\002\000\022\006\ufffb\007" +
    "\ufffb\010\ufffb\011\ufffb\013\ufffb\014\ufffb\015\ufffb\033\ufffb" +
    "\001\002\000\022\006\uffd9\007\uffd9\010\uffd9\011\uffd9\013" +
    "\uffd9\014\uffd9\015\uffd9\033\uffd9\001\002\000\022\006\ufff5" +
    "\007\ufff5\010\ufff5\011\ufff5\013\ufff5\014\ufff5\015\ufff5\033" +
    "\ufff5\001\002\000\004\002\uffff\001\002\000\004\040\136" +
    "\001\002\000\012\016\130\025\125\026\127\037\126\001" +
    "\002\000\004\042\134\001\002\000\022\006\ufff1\007\ufff1" +
    "\010\ufff1\011\ufff1\013\ufff1\014\ufff1\015\ufff1\033\ufff1\001" +
    "\002\000\004\037\133\001\002\000\004\042\131\001\002" +
    "\000\004\037\132\001\002\000\022\006\uffef\007\uffef\010" +
    "\uffef\011\uffef\013\uffef\014\uffef\015\uffef\033\uffef\001\002" +
    "\000\022\006\uffee\007\uffee\010\uffee\011\uffee\013\uffee\014" +
    "\uffee\015\uffee\033\uffee\001\002\000\004\037\135\001\002" +
    "\000\022\006\ufff0\007\ufff0\010\ufff0\011\ufff0\013\ufff0\014" +
    "\ufff0\015\ufff0\033\ufff0\001\002\000\004\037\137\001\002" +
    "\000\022\006\uffed\007\uffed\010\uffed\011\uffed\013\uffed\014" +
    "\uffed\015\uffed\033\uffed\001\002\000\020\006\037\007\043" +
    "\010\036\011\033\013\040\014\032\015\045\001\002\000" +
    "\022\006\037\007\043\010\036\011\033\013\040\014\032" +
    "\015\045\033\142\001\002\000\004\014\143\001\002\000" +
    "\004\030\144\001\002\000\006\027\060\040\061\001\002" +
    "\000\004\031\146\001\002\000\004\037\147\001\002\000" +
    "\022\006\uffda\007\uffda\010\uffda\011\uffda\013\uffda\014\uffda" +
    "\015\uffda\033\uffda\001\002\000\004\040\163\001\002\000" +
    "\012\016\155\025\152\026\154\037\153\001\002\000\004" +
    "\042\161\001\002\000\022\006\uffec\007\uffec\010\uffec\011" +
    "\uffec\013\uffec\014\uffec\015\uffec\033\uffec\001\002\000\004" +
    "\037\160\001\002\000\004\042\156\001\002\000\004\037" +
    "\157\001\002\000\022\006\uffea\007\uffea\010\uffea\011\uffea" +
    "\013\uffea\014\uffea\015\uffea\033\uffea\001\002\000\022\006" +
    "\uffe9\007\uffe9\010\uffe9\011\uffe9\013\uffe9\014\uffe9\015\uffe9" +
    "\033\uffe9\001\002\000\004\037\162\001\002\000\022\006" +
    "\uffeb\007\uffeb\010\uffeb\011\uffeb\013\uffeb\014\uffeb\015\uffeb" +
    "\033\uffeb\001\002\000\004\037\164\001\002\000\022\006" +
    "\uffe8\007\uffe8\010\uffe8\011\uffe8\013\uffe8\014\uffe8\015\uffe8" +
    "\033\uffe8\001\002\000\006\016\167\025\166\001\002\000" +
    "\004\005\176\001\002\000\004\005\170\001\002\000\006" +
    "\005\171\040\172\001\002\000\004\037\175\001\002\000" +
    "\004\005\173\001\002\000\004\037\174\001\002\000\022" +
    "\006\uffe4\007\uffe4\010\uffe4\011\uffe4\013\uffe4\014\uffe4\015" +
    "\uffe4\033\uffe4\001\002\000\022\006\uffe6\007\uffe6\010\uffe6" +
    "\011\uffe6\013\uffe6\014\uffe6\015\uffe6\033\uffe6\001\002\000" +
    "\006\005\177\040\200\001\002\000\004\037\203\001\002" +
    "\000\004\005\201\001\002\000\004\037\202\001\002\000" +
    "\022\006\uffe5\007\uffe5\010\uffe5\011\uffe5\013\uffe5\014\uffe5" +
    "\015\uffe5\033\uffe5\001\002\000\022\006\uffe7\007\uffe7\010" +
    "\uffe7\011\uffe7\013\uffe7\014\uffe7\015\uffe7\033\uffe7\001\002" +
    "\000\006\027\060\040\061\001\002\000\004\031\206\001" +
    "\002\000\004\032\207\001\002\000\020\006\037\007\043" +
    "\010\036\011\033\013\040\014\032\015\045\001\002\000" +
    "\022\006\037\007\043\010\036\011\033\013\040\014\032" +
    "\015\045\033\211\001\002\000\024\006\uffe3\007\uffe3\010" +
    "\uffe3\011\uffe3\012\212\013\uffe3\014\uffe3\015\uffe3\033\uffe3" +
    "\001\002\000\004\032\213\001\002\000\020\006\037\007" +
    "\043\010\036\011\033\013\040\014\032\015\045\001\002" +
    "\000\022\006\037\007\043\010\036\011\033\013\040\014" +
    "\032\015\045\033\215\001\002\000\022\006\uffdc\007\uffdc" +
    "\010\uffdc\011\uffdc\013\uffdc\014\uffdc\015\uffdc\033\uffdc\001" +
    "\002\000\006\027\060\040\061\001\002\000\004\031\220" +
    "\001\002\000\004\032\221\001\002\000\020\006\037\007" +
    "\043\010\036\011\033\013\040\014\032\015\045\001\002" +
    "\000\022\006\037\007\043\010\036\011\033\013\040\014" +
    "\032\015\045\033\223\001\002\000\022\006\uffdb\007\uffdb" +
    "\010\uffdb\011\uffdb\013\uffdb\014\uffdb\015\uffdb\033\uffdb\001" +
    "\002\000\004\030\225\001\002\000\004\031\226\001\002" +
    "\000\004\032\227\001\002\000\020\006\037\007\043\010" +
    "\036\011\033\013\040\014\032\015\045\001\002\000\022" +
    "\006\037\007\043\010\036\011\033\013\040\014\032\015" +
    "\045\033\231\001\002\000\004\002\000\001\002\000\010" +
    "\017\016\020\015\031\233\001\002\000\020\002\uffca\017" +
    "\uffca\020\uffca\021\uffca\022\uffca\030\uffca\031\uffca\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\232\000\014\002\003\015\013\016\010\017\004\020" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\015\231\016\010\017\004\020\011\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\020\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\016" +
    "\024\017\004\020\011\001\001\000\010\016\016\017\004" +
    "\020\011\001\001\000\004\020\017\001\001\000\002\001" +
    "\001\000\006\017\023\020\011\001\001\000\006\017\022" +
    "\020\011\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\003\043\004\034\006\041\007\040\010\030\011" +
    "\045\012\033\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\004" +
    "\114\006\116\007\115\010\112\011\120\012\113\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\047\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\013\056\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\072\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\104\001\001\000\002\001\001\000\004\005" +
    "\106\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\003\111\004\034\006\041\007\040\010\030\011\045\012" +
    "\033\001\001\000\016\004\114\006\116\007\115\010\112" +
    "\011\120\012\113\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\003\140\004\034\006\041\007\040\010\030\011\045" +
    "\012\033\001\001\000\016\004\114\006\116\007\115\010" +
    "\112\011\120\012\113\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\144\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\204\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\003\207\004\034\006\041\007\040" +
    "\010\030\011\045\012\033\001\001\000\016\004\114\006" +
    "\116\007\115\010\112\011\120\012\113\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\003\213\004\034\006" +
    "\041\007\040\010\030\011\045\012\033\001\001\000\016" +
    "\004\114\006\116\007\115\010\112\011\120\012\113\001" +
    "\001\000\002\001\001\000\004\013\216\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\003\221\004\034\006" +
    "\041\007\040\010\030\011\045\012\033\001\001\000\016" +
    "\004\114\006\116\007\115\010\112\011\120\012\113\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\003\227\004\034\006\041\007" +
    "\040\010\030\011\045\012\033\001\001\000\016\004\114" +
    "\006\116\007\115\010\112\011\120\012\113\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    private boolean errorEncontrado = false;
    private Double resultado = null;

    public void syntax_error(Symbol s){
        this.s = s;
        this.errorEncontrado = true;
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        this.s = s;
        this.errorEncontrado = true;
    }

    public Symbol getS(){
        return this.s;
    }

    public boolean hayError(){
        return this.errorEncontrado;
    }

    public void resetError(){
        this.s = null;
        this.errorEncontrado = false;
        this.resultado = null;
    }

    public void setResultado(Double r){
        this.resultado = r;
    }

    public Double getResultado(){
        return this.resultado;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$sintax$actions {
  private final sintax parser;

  /** Constructor */
  CUP$sintax$actions(sintax parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$sintax$do_action_part00000000(
    int                        CUP$sintax$act_num,
    java_cup.runtime.lr_parser CUP$sintax$parser,
    java.util.Stack            CUP$sintax$stack,
    int                        CUP$sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$sintax$result;

      /* select the action based on the action number */
      switch (CUP$sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		RESULT = start_val;
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$sintax$parser.done_parsing();
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= Int Main Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= Main Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= EXPRESION 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 parser.setResultado(e); 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTENCIA ::= SENTENCIA DECLARACION 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= SENTENCIA IF 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= IF 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= SENTENCIA IF_ELSE 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= IF_ELSE 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= SENTENCIA WHILE 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= WHILE 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= SENTENCIA DO_WHILE 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= DO_WHILE 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= SENTENCIA FOR 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTENCIA ::= FOR 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // DECLARACION ::= Int Identificador P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // DECLARACION ::= Int Identificador Op_atribucion Numero P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // DECLARACION ::= Int Identificador Igual Numero P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARACION ::= Int Identificador Op_incremento P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARACION ::= Int Op_incremento Identificador P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DECLARACION ::= T_dato Identificador P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // DECLARACION ::= T_dato Identificador Op_atribucion Numero P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // DECLARACION ::= T_dato Identificador Igual Numero P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // DECLARACION ::= T_dato Identificador Op_incremento P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DECLARACION ::= T_dato Op_incremento Identificador P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // DECLARACION ::= Cadena Identificador Op_atribucion Comillas Comillas P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // DECLARACION ::= Cadena Identificador Igual Comillas Comillas P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // DECLARACION ::= Cadena Identificador Op_atribucion Comillas Identificador Comillas P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // DECLARACION ::= Cadena Identificador Igual Comillas Identificador Comillas P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // IF ::= If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("IF",4, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // SENTENCIA_BOOLEANA ::= Op_booleano 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Op_booleano 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Numero 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Identificador 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Comillas Comillas 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // SENTENCIA_BOOLEANA ::= Identificador Op_relacional Comillas Identificador Comillas 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // IF_ELSE ::= If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a SENTENCIA Llave_c Else Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("IF_ELSE",5, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-10)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // WHILE ::= While Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("WHILE",6, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // DO_WHILE ::= Do Llave_a SENTENCIA Llave_c While Parentesis_a SENTENCIA_BOOLEANA Parentesis_c P_coma 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DO_WHILE",7, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-8)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // FOR ::= For Parentesis_a SENTENCIA_FOR Parentesis_c Llave_a SENTENCIA Llave_c 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FOR",8, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // SENTENCIA_FOR ::= T_dato Identificador Igual Numero P_coma SENTENCIA_BOOLEANA P_coma DECLARACION_FOR 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_FOR",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-7)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // SENTENCIA_FOR ::= Identificador Igual Numero P_coma SENTENCIA_BOOLEANA P_coma DECLARACION_FOR 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_FOR",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // DECLARACION_FOR ::= Identificador Op_atribucion Numero 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION_FOR",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // DECLARACION_FOR ::= Identificador Op_incremento 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION_FOR",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // DECLARACION_FOR ::= Op_incremento Identificador 
            {
              Object RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION_FOR",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // EXPRESION ::= EXPRESION Suma TERMINO 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = e + t; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // EXPRESION ::= EXPRESION Resta TERMINO 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = e - t; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // EXPRESION ::= TERMINO 
            {
              Double RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = t; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // TERMINO ::= TERMINO Multiplicacion FACTOR 
            {
              Double RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = t * f; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",12, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // TERMINO ::= TERMINO Division FACTOR 
            {
              Double RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = (f != 0) ? t / f : 0.0; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",12, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // TERMINO ::= FACTOR 
            {
              Double RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = f; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",12, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // TERMINO ::= TERMINO FACTOR_PAREN 
            {
              Double RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = t * f; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",12, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // FACTOR ::= Numero 
            {
              Double RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = Double.parseDouble(n); 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",13, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // FACTOR ::= FACTOR_PAREN 
            {
              Double RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		Double p = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = p; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",13, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // FACTOR_PAREN ::= Parentesis_a EXPRESION Parentesis_c 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 RESULT = e; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR_PAREN",14, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$sintax$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$sintax$do_action(
    int                        CUP$sintax$act_num,
    java_cup.runtime.lr_parser CUP$sintax$parser,
    java.util.Stack            CUP$sintax$stack,
    int                        CUP$sintax$top)
    throws java.lang.Exception
    {
              return CUP$sintax$do_action_part00000000(
                               CUP$sintax$act_num,
                               CUP$sintax$parser,
                               CUP$sintax$stack,
                               CUP$sintax$top);
    }
}

}
