
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectofinalcompilador.Sintactico;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class sintax extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public sintax() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\116\000\002\002\004\000\002\002\003\000\002\003" +
    "\003\000\002\003\003\000\002\004\010\000\002\004\007" +
    "\000\002\005\014\000\002\005\012\000\002\006\003\000" +
    "\002\006\002\000\002\007\006\000\002\007\006\000\002" +
    "\007\004\000\002\010\005\000\002\011\005\000\002\013" +
    "\003\000\002\013\002\000\002\012\004\000\002\012\003" +
    "\000\002\014\004\000\002\014\004\000\002\014\005\000" +
    "\002\014\007\000\002\014\007\000\002\014\004\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\005\000\002\014\004" +
    "\000\002\032\012\000\002\033\003\000\002\033\002\000" +
    "\002\034\004\000\002\034\003\000\002\035\006\000\002" +
    "\036\005\000\002\036\002\000\002\026\011\000\002\026" +
    "\014\000\002\026\010\000\002\031\003\000\002\031\002" +
    "\000\002\037\002\000\002\027\011\000\002\027\011\000" +
    "\002\027\011\000\002\027\011\000\002\015\004\000\002" +
    "\015\006\000\002\016\005\000\002\025\003\000\002\025" +
    "\003\000\002\025\003\000\002\017\003\000\002\017\003" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\030\005\000\002\030\005\000\002\030\003\000\002" +
    "\030\005\000\002\021\005\000\002\021\005\000\002\021" +
    "\003\000\002\022\005\000\002\022\005\000\002\022\003" +
    "\000\002\023\003\000\002\023\004\000\002\023\003\000" +
    "\002\023\005\000\002\020\003\000\002\020\005\000\002" +
    "\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\010\034\007\035\005\041\004\001\002\000" +
    "\036\006\052\007\062\012\066\024\054\040\061\041\004" +
    "\042\ufff1\045\064\047\047\051\041\052\056\054\063\060" +
    "\055\061\051\001\002\000\004\061\255\001\002\000\004" +
    "\002\ufffe\001\002\000\004\035\014\001\002\000\004\002" +
    "\013\001\002\000\004\002\000\001\002\000\004\002\uffff" +
    "\001\002\000\004\002\001\001\002\000\004\061\015\001" +
    "\002\000\004\024\016\001\002\000\006\034\021\037\017" +
    "\001\002\000\004\030\246\001\002\000\004\025\245\001" +
    "\002\000\004\036\022\001\002\000\004\037\023\001\002" +
    "\000\004\030\024\001\002\000\004\022\025\001\002\000" +
    "\006\023\ufff8\040\027\001\002\000\004\023\037\001\002" +
    "\000\006\026\031\061\032\001\002\000\004\023\ufff9\001" +
    "\002\000\004\027\035\001\002\000\006\023\ufff5\026\033" +
    "\001\002\000\004\027\034\001\002\000\004\023\ufff6\001" +
    "\002\000\004\061\036\001\002\000\004\023\ufff7\001\002" +
    "\000\004\024\040\001\002\000\036\006\052\007\062\012" +
    "\066\024\054\025\ufff1\040\061\041\004\045\064\047\047" +
    "\051\041\052\056\054\063\060\055\061\051\001\002\000" +
    "\004\022\235\001\002\000\004\025\234\001\002\000\050" +
    "\006\uffe4\007\uffe4\010\uffe4\012\uffe4\024\uffe4\025\uffe4\040" +
    "\uffe4\041\uffe4\042\uffe4\044\uffe4\045\uffe4\046\uffe4\047\uffe4" +
    "\050\uffe4\051\uffe4\052\uffe4\054\uffe4\060\uffe4\061\uffe4\001" +
    "\002\000\004\031\233\001\002\000\044\006\uffef\007\uffef" +
    "\012\uffef\024\uffef\025\uffef\040\uffef\041\uffef\042\uffef\045" +
    "\uffef\046\uffef\047\uffef\050\uffef\051\uffef\052\uffef\054\uffef" +
    "\060\uffef\061\uffef\001\002\000\050\006\uffe5\007\uffe5\010" +
    "\uffe5\012\uffe5\024\uffe5\025\uffe5\040\uffe5\041\uffe5\042\uffe5" +
    "\044\uffe5\045\uffe5\046\uffe5\047\uffe5\050\uffe5\051\uffe5\052" +
    "\uffe5\054\uffe5\060\uffe5\061\uffe5\001\002\000\004\031\232" +
    "\001\002\000\050\006\uffe6\007\uffe6\010\uffe6\012\uffe6\024" +
    "\uffe6\025\uffe6\040\uffe6\041\uffe6\042\uffe6\044\uffe6\045\uffe6" +
    "\046\uffe6\047\uffe6\050\uffe6\051\uffe6\052\uffe6\054\uffe6\060" +
    "\uffe6\061\uffe6\001\002\000\010\014\150\064\146\065\227" +
    "\001\002\000\004\061\uffc7\001\002\000\050\006\uffe8\007" +
    "\uffe8\010\uffe8\012\uffe8\024\uffe8\025\uffe8\040\uffe8\041\uffe8" +
    "\042\uffe8\044\uffe8\045\uffe8\046\uffe8\047\uffe8\050\uffe8\051" +
    "\uffe8\052\uffe8\054\uffe8\060\uffe8\061\uffe8\001\002\000\036" +
    "\006\052\007\062\012\066\024\054\025\ufff1\040\061\041" +
    "\004\045\064\047\047\051\041\052\056\054\063\060\055" +
    "\061\051\001\002\000\004\061\uffc6\001\002\000\004\022" +
    "\220\001\002\000\004\031\217\001\002\000\050\006\uffe7" +
    "\007\uffe7\010\uffe7\012\uffe7\024\uffe7\025\uffe7\040\uffe7\041" +
    "\uffe7\042\uffe7\044\uffe7\045\uffe7\046\uffe7\047\uffe7\050\uffe7" +
    "\051\uffe7\052\uffe7\054\uffe7\060\uffe7\061\uffe7\001\002\000" +
    "\004\061\uffc5\001\002\000\004\022\201\001\002\000\020" +
    "\016\101\022\117\031\177\057\077\061\121\063\153\066" +
    "\152\001\002\000\004\022\155\001\002\000\004\061\145" +
    "\001\002\000\004\022\071\001\002\000\044\006\052\007" +
    "\062\012\066\024\054\025\ufff2\040\061\041\004\042\ufff2" +
    "\045\064\046\ufff2\047\047\050\ufff2\051\041\052\056\054" +
    "\063\060\055\061\051\001\002\000\044\006\ufff0\007\ufff0" +
    "\012\ufff0\024\ufff0\025\ufff0\040\ufff0\041\ufff0\042\ufff0\045" +
    "\ufff0\046\ufff0\047\ufff0\050\ufff0\051\ufff0\052\ufff0\054\ufff0" +
    "\060\ufff0\061\ufff0\001\002\000\014\016\101\022\073\057" +
    "\077\061\075\063\072\001\002\000\004\023\uffc2\001\002" +
    "\000\014\016\101\022\073\057\077\061\121\063\072\001" +
    "\002\000\024\014\uffbb\015\uffbb\016\uffbb\017\uffbb\020\uffbb" +
    "\023\uffbb\031\uffbb\056\uffbb\062\uffbb\001\002\000\020\014" +
    "\uffb8\015\uffb8\016\uffb8\017\uffb8\020\uffb8\023\133\062\uffb8" +
    "\001\002\000\024\014\uffbe\015\uffbe\016\uffbe\017\126\020" +
    "\125\023\uffbe\031\uffbe\056\uffbe\062\uffbe\001\002\000\024" +
    "\014\uffba\015\uffba\016\uffba\017\uffba\020\uffba\023\uffba\031" +
    "\uffba\056\uffba\062\uffba\001\002\000\012\014\116\015\115" +
    "\016\114\062\113\001\002\000\004\057\112\001\002\000" +
    "\004\023\103\001\002\000\006\011\104\024\105\001\002" +
    "\000\034\006\052\007\062\012\066\024\054\040\061\041" +
    "\004\045\064\047\047\051\041\052\056\054\063\060\055" +
    "\061\051\001\002\000\036\006\052\007\062\012\066\024" +
    "\054\025\ufff1\040\061\041\004\045\064\047\047\051\041" +
    "\052\056\054\063\060\055\061\051\001\002\000\004\025" +
    "\107\001\002\000\050\006\uffd1\007\uffd1\010\uffd1\012\uffd1" +
    "\024\uffd1\025\uffd1\040\uffd1\041\uffd1\042\uffd1\044\uffd1\045" +
    "\uffd1\046\uffd1\047\uffd1\050\uffd1\051\uffd1\052\uffd1\054\uffd1" +
    "\060\uffd1\061\uffd1\001\002\000\004\044\111\001\002\000" +
    "\050\006\uffd3\007\uffd3\010\uffd3\012\uffd3\024\uffd3\025\uffd3" +
    "\040\uffd3\041\uffd3\042\uffd3\044\uffd3\045\uffd3\046\uffd3\047" +
    "\uffd3\050\uffd3\051\uffd3\052\uffd3\054\uffd3\060\uffd3\061\uffd3" +
    "\001\002\000\024\014\uffb9\015\uffb9\016\uffb9\017\uffb9\020" +
    "\uffb9\023\uffb9\031\uffb9\056\uffb9\062\uffb9\001\002\000\012" +
    "\016\101\022\117\057\077\061\121\001\002\000\012\016" +
    "\101\022\117\057\077\061\121\001\002\000\012\016\101" +
    "\022\117\057\077\061\121\001\002\000\012\016\101\022" +
    "\117\057\077\061\121\001\002\000\012\016\101\022\117" +
    "\057\077\061\121\001\002\000\010\015\115\016\114\023" +
    "\uffc3\001\002\000\024\014\uffb8\015\uffb8\016\uffb8\017\uffb8" +
    "\020\uffb8\023\uffb8\031\uffb8\056\uffb8\062\uffb8\001\002\000" +
    "\010\015\115\016\114\023\123\001\002\000\024\014\uffb7" +
    "\015\uffb7\016\uffb7\017\uffb7\020\uffb7\023\uffb7\031\uffb7\056" +
    "\uffb7\062\uffb7\001\002\000\024\014\uffc0\015\uffc0\016\uffc0" +
    "\017\126\020\125\023\uffc0\031\uffc0\056\uffc0\062\uffc0\001" +
    "\002\000\012\016\101\022\117\057\077\061\121\001\002" +
    "\000\012\016\101\022\117\057\077\061\121\001\002\000" +
    "\024\014\uffbd\015\uffbd\016\uffbd\017\uffbd\020\uffbd\023\uffbd" +
    "\031\uffbd\056\uffbd\062\uffbd\001\002\000\024\014\uffbc\015" +
    "\uffbc\016\uffbc\017\uffbc\020\uffbc\023\uffbc\031\uffbc\056\uffbc" +
    "\062\uffbc\001\002\000\024\014\uffbf\015\uffbf\016\uffbf\017" +
    "\126\020\125\023\uffbf\031\uffbf\056\uffbf\062\uffbf\001\002" +
    "\000\010\015\115\016\114\023\uffc4\001\002\000\006\011" +
    "\135\024\134\001\002\000\036\006\052\007\062\012\066" +
    "\024\054\025\ufff1\040\061\041\004\045\064\047\047\051" +
    "\041\052\056\054\063\060\055\061\051\001\002\000\034" +
    "\006\052\007\062\012\066\024\054\040\061\041\004\045" +
    "\064\047\047\051\041\052\056\054\063\060\055\061\051" +
    "\001\002\000\004\044\137\001\002\000\050\006\uffd2\007" +
    "\uffd2\010\uffd2\012\uffd2\024\uffd2\025\uffd2\040\uffd2\041\uffd2" +
    "\042\uffd2\044\uffd2\045\uffd2\046\uffd2\047\uffd2\050\uffd2\051" +
    "\uffd2\052\uffd2\054\uffd2\060\uffd2\061\uffd2\001\002\000\004" +
    "\025\141\001\002\000\050\006\uffd0\007\uffd0\010\uffd0\012" +
    "\uffd0\024\uffd0\025\uffd0\040\uffd0\041\uffd0\042\uffd0\044\uffd0" +
    "\045\uffd0\046\uffd0\047\uffd0\050\uffd0\051\uffd0\052\uffd0\054" +
    "\uffd0\060\uffd0\061\uffd0\001\002\000\014\014\116\015\115" +
    "\016\114\023\123\062\113\001\002\000\004\023\144\001" +
    "\002\000\004\023\uffc1\001\002\000\010\014\150\031\uffcf" +
    "\064\146\001\002\000\016\016\uffc8\022\uffc8\057\uffc8\061" +
    "\uffc8\063\uffc8\066\uffc8\001\002\000\016\016\101\022\117" +
    "\057\077\061\121\063\153\066\152\001\002\000\016\016" +
    "\uffc9\022\uffc9\057\uffc9\061\uffc9\063\uffc9\066\uffc9\001\002" +
    "\000\004\031\uffce\001\002\000\006\031\uffca\056\uffca\001" +
    "\002\000\006\031\uffcb\056\uffcb\001\002\000\012\015\115" +
    "\016\114\031\uffcc\056\uffcc\001\002\000\012\016\101\022" +
    "\117\057\077\061\121\001\002\000\010\015\115\016\114" +
    "\023\157\001\002\000\004\024\160\001\002\000\010\025" +
    "\uffdf\046\162\050\uffdf\001\002\000\006\025\uffda\050\172" +
    "\001\002\000\016\016\101\022\117\057\077\061\121\063" +
    "\153\066\152\001\002\000\010\025\uffdd\046\uffdd\050\uffdd" +
    "\001\002\000\010\025\uffe0\046\162\050\uffe0\001\002\000" +
    "\010\025\uffde\046\uffde\050\uffde\001\002\000\004\056\167" +
    "\001\002\000\042\006\052\007\062\012\066\024\054\025" +
    "\ufff1\040\061\041\004\045\064\046\ufff1\047\047\050\ufff1" +
    "\051\041\052\056\054\063\060\055\061\051\001\002\000" +
    "\010\025\uffdc\046\uffdc\050\uffdc\001\002\000\004\025\175" +
    "\001\002\000\004\056\173\001\002\000\036\006\052\007" +
    "\062\012\066\024\054\025\ufff1\040\061\041\004\045\064" +
    "\047\047\051\041\052\056\054\063\060\055\061\051\001" +
    "\002\000\004\025\uffdb\001\002\000\050\006\uffe1\007\uffe1" +
    "\010\uffe1\012\uffe1\024\uffe1\025\uffe1\040\uffe1\041\uffe1\042" +
    "\uffe1\044\uffe1\045\uffe1\046\uffe1\047\uffe1\050\uffe1\051\uffe1" +
    "\052\uffe1\054\uffe1\060\uffe1\061\uffe1\001\002\000\004\031" +
    "\200\001\002\000\050\006\uffe2\007\uffe2\010\uffe2\012\uffe2" +
    "\024\uffe2\025\uffe2\040\uffe2\041\uffe2\042\uffe2\044\uffe2\045" +
    "\uffe2\046\uffe2\047\uffe2\050\uffe2\051\uffe2\052\uffe2\054\uffe2" +
    "\060\uffe2\061\uffe2\001\002\000\050\006\uffe3\007\uffe3\010" +
    "\uffe3\012\uffe3\024\uffe3\025\uffe3\040\uffe3\041\uffe3\042\uffe3" +
    "\044\uffe3\045\uffe3\046\uffe3\047\uffe3\050\uffe3\051\uffe3\052" +
    "\uffe3\054\uffe3\060\uffe3\061\uffe3\001\002\000\014\016\101" +
    "\022\073\057\077\061\202\063\072\001\002\000\020\014" +
    "\uffb8\015\uffb8\016\uffb8\017\uffb8\020\uffb8\023\214\062\uffb8" +
    "\001\002\000\004\023\204\001\002\000\036\006\uffd5\007" +
    "\uffd5\012\uffd5\024\uffd5\040\uffd5\041\uffd5\045\uffd5\047\uffd5" +
    "\051\uffd5\052\uffd5\053\205\054\uffd5\060\uffd5\061\uffd5\001" +
    "\002\000\034\006\uffd6\007\uffd6\012\uffd6\024\uffd6\040\uffd6" +
    "\041\uffd6\045\uffd6\047\uffd6\051\uffd6\052\uffd6\054\uffd6\060" +
    "\uffd6\061\uffd6\001\002\000\034\006\uffd4\007\uffd4\012\uffd4" +
    "\024\uffd4\040\uffd4\041\uffd4\045\uffd4\047\uffd4\051\uffd4\052" +
    "\uffd4\054\uffd4\060\uffd4\061\uffd4\001\002\000\034\006\052" +
    "\007\062\012\066\024\054\040\061\041\004\045\064\047" +
    "\047\051\041\052\056\054\063\060\055\061\051\001\002" +
    "\000\050\006\uffd9\007\uffd9\010\211\012\uffd9\024\uffd9\025" +
    "\uffd9\040\uffd9\041\uffd9\042\uffd9\044\uffd9\045\uffd9\046\uffd9" +
    "\047\uffd9\050\uffd9\051\uffd9\052\uffd9\054\uffd9\060\uffd9\061" +
    "\uffd9\001\002\000\034\006\uffd4\007\uffd4\012\uffd4\024\uffd4" +
    "\040\uffd4\041\uffd4\045\uffd4\047\uffd4\051\uffd4\052\uffd4\054" +
    "\uffd4\060\uffd4\061\uffd4\001\002\000\034\006\052\007\062" +
    "\012\066\024\054\040\061\041\004\045\064\047\047\051" +
    "\041\052\056\054\063\060\055\061\051\001\002\000\050" +
    "\006\uffd8\007\uffd8\010\uffd8\012\uffd8\024\uffd8\025\uffd8\040" +
    "\uffd8\041\uffd8\042\uffd8\044\uffd8\045\uffd8\046\uffd8\047\uffd8" +
    "\050\uffd8\051\uffd8\052\uffd8\054\uffd8\060\uffd8\061\uffd8\001" +
    "\002\000\036\006\uffd5\007\uffd5\012\uffd5\024\uffd5\040\uffd5" +
    "\041\uffd5\045\uffd5\047\uffd5\051\uffd5\052\uffd5\053\205\054" +
    "\uffd5\060\uffd5\061\uffd5\001\002\000\034\006\052\007\062" +
    "\012\066\024\054\040\061\041\004\045\064\047\047\051" +
    "\041\052\056\054\063\060\055\061\051\001\002\000\050" +
    "\006\uffd7\007\uffd7\010\uffd7\012\uffd7\024\uffd7\025\uffd7\040" +
    "\uffd7\041\uffd7\042\uffd7\044\uffd7\045\uffd7\046\uffd7\047\uffd7" +
    "\050\uffd7\051\uffd7\052\uffd7\054\uffd7\060\uffd7\061\uffd7\001" +
    "\002\000\050\006\uffed\007\uffed\010\uffed\012\uffed\024\uffed" +
    "\025\uffed\040\uffed\041\uffed\042\uffed\044\uffed\045\uffed\046" +
    "\uffed\047\uffed\050\uffed\051\uffed\052\uffed\054\uffed\060\uffed" +
    "\061\uffed\001\002\000\004\061\221\001\002\000\004\023" +
    "\222\001\002\000\004\031\223\001\002\000\050\006\uffea" +
    "\007\uffea\010\uffea\012\uffea\024\uffea\025\uffea\040\uffea\041" +
    "\uffea\042\uffea\044\uffea\045\uffea\046\uffea\047\uffea\050\uffea" +
    "\051\uffea\052\uffea\054\uffea\060\uffea\061\uffea\001\002\000" +
    "\004\025\225\001\002\000\050\006\ufff3\007\ufff3\010\ufff3" +
    "\012\ufff3\024\ufff3\025\ufff3\040\ufff3\041\ufff3\042\ufff3\044" +
    "\ufff3\045\ufff3\046\ufff3\047\ufff3\050\ufff3\051\ufff3\052\ufff3" +
    "\054\ufff3\060\ufff3\061\ufff3\001\002\000\016\016\101\022" +
    "\117\057\077\061\121\063\153\066\152\001\002\000\004" +
    "\031\230\001\002\000\050\006\uffec\007\uffec\010\uffec\012" +
    "\uffec\024\uffec\025\uffec\040\uffec\041\uffec\042\uffec\044\uffec" +
    "\045\uffec\046\uffec\047\uffec\050\uffec\051\uffec\052\uffec\054" +
    "\uffec\060\uffec\061\uffec\001\002\000\004\031\uffcd\001\002" +
    "\000\050\006\uffe9\007\uffe9\010\uffe9\012\uffe9\024\uffe9\025" +
    "\uffe9\040\uffe9\041\uffe9\042\uffe9\044\uffe9\045\uffe9\046\uffe9" +
    "\047\uffe9\050\uffe9\051\uffe9\052\uffe9\054\uffe9\060\uffe9\061" +
    "\uffe9\001\002\000\050\006\uffee\007\uffee\010\uffee\012\uffee" +
    "\024\uffee\025\uffee\040\uffee\041\uffee\042\uffee\044\uffee\045" +
    "\uffee\046\uffee\047\uffee\050\uffee\051\uffee\052\uffee\054\uffee" +
    "\060\uffee\061\uffee\001\002\000\004\025\ufffb\001\002\000" +
    "\014\016\101\022\117\057\077\061\121\066\236\001\002" +
    "\000\006\015\243\023\uffb6\001\002\000\004\023\241\001" +
    "\002\000\010\015\115\016\114\023\uffb4\001\002\000\004" +
    "\031\242\001\002\000\050\006\uffeb\007\uffeb\010\uffeb\012" +
    "\uffeb\024\uffeb\025\uffeb\040\uffeb\041\uffeb\042\uffeb\044\uffeb" +
    "\045\uffeb\046\uffeb\047\uffeb\050\uffeb\051\uffeb\052\uffeb\054" +
    "\uffeb\060\uffeb\061\uffeb\001\002\000\012\016\101\022\117" +
    "\057\077\061\121\001\002\000\010\015\115\016\114\023" +
    "\uffb5\001\002\000\004\002\ufffd\001\002\000\004\022\247" +
    "\001\002\000\006\023\ufff8\040\027\001\002\000\004\023" +
    "\251\001\002\000\004\024\252\001\002\000\036\006\052" +
    "\007\062\012\066\024\054\025\ufff1\040\061\041\004\045" +
    "\064\047\047\051\041\052\056\054\063\060\055\061\051" +
    "\001\002\000\004\025\254\001\002\000\004\025\ufffa\001" +
    "\002\000\004\024\256\001\002\000\006\034\021\037\017" +
    "\001\002\000\004\025\260\001\002\000\004\002\ufffc\001" +
    "\002\000\004\042\262\001\002\000\052\002\ufff4\006\ufff4" +
    "\007\ufff4\010\ufff4\012\ufff4\024\ufff4\025\ufff4\040\ufff4\041" +
    "\ufff4\042\ufff4\044\ufff4\045\ufff4\046\ufff4\047\ufff4\050\ufff4" +
    "\051\ufff4\052\ufff4\054\ufff4\060\ufff4\061\ufff4\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\012\002\007\003\010\004\011\010\005\001" +
    "\001\000\030\010\045\011\042\012\066\013\260\014\044" +
    "\015\043\016\056\024\064\026\052\027\057\032\047\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\017\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\025\007\027\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\010\045\011\042\012\066\013\041\014\044\015\043\016" +
    "\056\024\064\026\052\027\057\032\047\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\017\225\001\001\000\002\001" +
    "\001\000\002\001\001\000\030\010\045\011\042\012\066" +
    "\013\223\014\044\015\043\016\056\024\064\026\052\027" +
    "\057\032\047\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\021\153\022\075\023\073\025\175" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\010\045\011\042\014\067\015\043\016\056" +
    "\024\064\026\052\027\057\032\047\001\001\000\002\001" +
    "\001\000\012\021\077\022\075\023\073\030\101\001\001" +
    "\000\002\001\001\000\012\021\141\022\075\023\073\030" +
    "\142\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\024\010\045" +
    "\011\042\014\107\015\043\016\056\024\064\026\052\027" +
    "\057\032\047\001\001\000\030\010\045\011\042\012\066" +
    "\013\105\014\044\015\043\016\056\024\064\026\052\027" +
    "\057\032\047\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\021\131\022\075\023\073\001\001\000\006\022\130" +
    "\023\073\001\001\000\006\022\123\023\073\001\001\000" +
    "\010\021\117\022\075\023\073\001\001\000\010\021\121" +
    "\022\075\023\073\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\023\127\001\001\000\004\023\126\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\030\010\045\011\042\012" +
    "\066\013\137\014\044\015\043\016\056\024\064\026\052" +
    "\027\057\032\047\001\001\000\024\010\045\011\042\014" +
    "\135\015\043\016\056\024\064\026\052\027\057\032\047" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\017\146\001\001\000\002\001" +
    "\001\000\012\021\153\022\075\023\073\025\150\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\021\155\022\075" +
    "\023\073\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\033\160\034\163\035\162\001\001\000\004\036\170" +
    "\001\001\000\012\021\153\022\075\023\073\025\165\001" +
    "\001\000\002\001\001\000\004\035\164\001\001\000\002" +
    "\001\001\000\002\001\001\000\030\010\045\011\042\012" +
    "\066\013\167\014\044\015\043\016\056\024\064\026\052" +
    "\027\057\032\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\030\010\045\011\042\012\066" +
    "\013\173\014\044\015\043\016\056\024\064\026\052\027" +
    "\057\032\047\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\021\077\022\075\023\073\030\202\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\031\205\001\001\000" +
    "\002\001\001\000\004\037\206\001\001\000\024\010\045" +
    "\011\042\014\207\015\043\016\056\024\064\026\052\027" +
    "\057\032\047\001\001\000\002\001\001\000\004\037\211" +
    "\001\001\000\024\010\045\011\042\014\212\015\043\016" +
    "\056\024\064\026\052\027\057\032\047\001\001\000\002" +
    "\001\001\000\004\031\214\001\001\000\024\010\045\011" +
    "\042\014\215\015\043\016\056\024\064\026\052\027\057" +
    "\032\047\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\021" +
    "\153\022\075\023\073\025\230\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\020\236\021\237" +
    "\022\075\023\073\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\021\243\022\075\023\073\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\247" +
    "\007\027\001\001\000\002\001\001\000\002\001\001\000" +
    "\030\010\045\011\042\012\066\013\252\014\044\015\043" +
    "\016\056\024\064\026\052\027\057\032\047\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\256\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private java_cup.runtime.Symbol s;
    private boolean errorEncontrado = false;
    private Object resultado = null;
    private proyectofinalcompilador.Semantico.TablaSimbolos tabla = new proyectofinalcompilador.Semantico.TablaSimbolos();
    private proyectofinalcompilador.CodigoIntermedio.GeneradorIntermedio genInter = new proyectofinalcompilador.CodigoIntermedio.GeneradorIntermedio();

    public void syntax_error(java_cup.runtime.Symbol s){
        this.s = s;
        this.errorEncontrado = true;
    }

    public void unrecovered_syntax_error(java_cup.runtime.Symbol s) throws java.lang.Exception {
        this.s = s;
        this.errorEncontrado = true;
    }

    public java_cup.runtime.Symbol getS(){
        return this.s;
    }

    public boolean hayError(){
        return this.errorEncontrado;
    }

    public void resetError(){
        this.s = null;
        this.errorEncontrado = false;
        this.resultado = null;
        this.tabla.limpiar();
        this.genInter.limpiar();
    }

    public void setResultado(Object r){
        this.resultado = r;
    }

    public Object getResultado(){
        return this.resultado;
    }

    public proyectofinalcompilador.Semantico.TablaSimbolos getTabla() {
        return this.tabla;
    }

    public proyectofinalcompilador.CodigoIntermedio.GeneradorIntermedio getGenInter() {
        return this.genInter;
    }

    private String[] descomponerExpresion(String expr) {
        int idx = expr.lastIndexOf("::::");
        if (idx == -1) return new String[] { expr, expr };
        return new String[] { expr.substring(0, idx), expr.substring(idx + 4) };
    }

    private String textoExpresion(String expr) {
        return descomponerExpresion(expr)[0];
    }

    private String valorExpresion(String expr) {
        return descomponerExpresion(expr)[1];
    }

    private String valorPorDefecto(String tipo) {
        String t = tipo.toLowerCase();
        if ("boolean".equals(t)) return "false";
        if ("char".equals(t) || "varchar".equals(t)) return "\"\"";
        return "0";
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$sintax$actions {
  private final sintax parser;

  /** Constructor */
  CUP$sintax$actions(sintax parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$sintax$do_action_part00000000(
    int                        CUP$sintax$act_num,
    java_cup.runtime.lr_parser CUP$sintax$parser,
    java.util.Stack            CUP$sintax$stack,
    int                        CUP$sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$sintax$result;

      /* select the action based on the action number */
      switch (CUP$sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		RESULT = start_val;
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$sintax$parser.done_parsing();
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= PROGRAMA 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = p; parser.setResultado(p); 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROGRAMA ::= CLASE 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = "Arbol Sintactico:\n" + c; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PROGRAMA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // PROGRAMA ::= BLOQUE_BEGIN 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = "Arbol Sintactico:\n" + b; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PROGRAMA",1, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CLASE ::= Public Class Identificador Llave_a METODO Llave_c 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String m = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "Clase " + id + "\n  " + m.replace("\n", "\n  ");
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CLASE",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // CLASE ::= Class Identificador Llave_a METODO Llave_c 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String m = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "Clase " + id + "\n  " + m.replace("\n", "\n  ");
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CLASE",2, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // METODO ::= Public Static Void Main Parentesis_a PARAMETROS_OPC Parentesis_c Llave_a LISTA_SENTENCIAS_OPC Llave_c 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "Metodo main(" + p + ")\n  Cuerpo:\n    " + (s.isEmpty() ? "<vacio>" : s.replace("\n", "\n    "));
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("METODO",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-9)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // METODO ::= Void Main Parentesis_a PARAMETROS_OPC Parentesis_c Llave_a LISTA_SENTENCIAS_OPC Llave_c 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "Metodo main(" + p + ")\n  Cuerpo:\n    " + (s.isEmpty() ? "<vacio>" : s.replace("\n", "\n    "));
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("METODO",3, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-7)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // PARAMETROS_OPC ::= PARAMETROS 
            {
              String RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = p; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS_OPC",4, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // PARAMETROS_OPC ::= 
            {
              String RESULT =null;
		 RESULT = ""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS_OPC",4, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // PARAMETROS ::= String_type Corchete_a Corchete_c Identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "String[]", "null", "local", idleft + 1));
        RESULT = "String[] " + id;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS",5, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // PARAMETROS ::= String_type Identificador Corchete_a Corchete_c 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "String[]", "null", "local", idleft + 1));
        RESULT = "String[] " + id;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS",5, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // PARAMETROS ::= String_type Identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, "String", "null", "local", idleft + 1));
        RESULT = "String " + id;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("PARAMETROS",5, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // BLOQUE_BEGIN ::= Begin LISTA_SENTENCIAS_OPC End 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "begin\n" + (s.isEmpty() ? "  <vacio>\n" : "  " + s.replace("\n", "\n  ") + "\n") + "end";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("BLOQUE_BEGIN",6, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // BLOQUE_LLAVES ::= Llave_a LISTA_SENTENCIAS_OPC Llave_c 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "{\n  "
                + (s.isEmpty() ? "<vacio>" : s.replace("\n", "\n  "))
                + "\n}";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("BLOQUE_LLAVES",7, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // LISTA_SENTENCIAS_OPC ::= LISTA_SENTENCIAS 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = s; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS_OPC",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // LISTA_SENTENCIAS_OPC ::= 
            {
              String RESULT =null;
		 RESULT = ""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS_OPC",9, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // LISTA_SENTENCIAS ::= LISTA_SENTENCIAS SENTENCIA 
            {
              String RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String ls = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = ls + "\n" + s; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",8, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // LISTA_SENTENCIAS ::= SENTENCIA 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = s; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",8, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // SENTENCIA ::= DECLARACION P_coma 
            {
              String RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 RESULT = d; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // SENTENCIA ::= ASIGNACION P_coma 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 RESULT = a; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // SENTENCIA ::= Identificador Op_incremento P_coma 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        parser.getGenInter().agregarOperacion(id, id, op.startsWith("+") ? "+" : "-", "1");
        parser.getTabla().asignarValor(id, id + " " + (op.startsWith("+") ? "+ 1" : "- 1"), idleft + 1);
        RESULT = "Incremento: " + id + op;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // SENTENCIA ::= Println Parentesis_a CONTENIDO_PARENTESIS Parentesis_c P_coma 
            {
              String RESULT =null;
		int cpleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int cpright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String cp = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		
        parser.getGenInter().agregarImpresion(valorExpresion(cp));
        RESULT = "Salida: println(" + textoExpresion(cp) + ")";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // SENTENCIA ::= In Parentesis_a Identificador Parentesis_c P_coma 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        parser.getGenInter().agregarLectura(id);
        RESULT = "Entrada: in(" + id + ")";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // SENTENCIA ::= Break P_coma 
            {
              String RESULT =null;
		 RESULT = "Break"; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // SENTENCIA ::= SENTENCIA_IF 
            {
              String RESULT =null;
		int sileft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int siright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String si = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = si; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // SENTENCIA ::= SENTENCIA_WHILE 
            {
              String RESULT =null;
		int swleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int swright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String sw = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = sw; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // SENTENCIA ::= SENTENCIA_SWITCH 
            {
              String RESULT =null;
		int ssleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int ssright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String ss = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = ss; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // SENTENCIA ::= BLOQUE_BEGIN 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = b; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // SENTENCIA ::= BLOQUE_LLAVES 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = b; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // SENTENCIA ::= Return VALOR P_coma 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 RESULT = "Return " + textoExpresion(v); 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // SENTENCIA ::= Return P_coma 
            {
              String RESULT =null;
		 RESULT = "Return"; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",10, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // SENTENCIA_SWITCH ::= Switch Parentesis_a EXPRESION Parentesis_c Llave_a CASOS_SWITCH_OPC DEFAULT_SWITCH_OPC Llave_c 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-5)).value;
		int csleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String cs = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        String casos = cs.isEmpty() ? "" : "  " + cs.replace("\n", "\n  ") + "\n";
        String porDefecto = d.isEmpty() ? "" : "  " + d.replace("\n", "\n  ") + "\n";
        RESULT = "Switch (" + textoExpresion(e) + ") {\n" + casos + porDefecto + "}";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_SWITCH",24, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-7)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // CASOS_SWITCH_OPC ::= CASOS_SWITCH 
            {
              String RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int csright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String cs = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = cs; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CASOS_SWITCH_OPC",25, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // CASOS_SWITCH_OPC ::= 
            {
              String RESULT =null;
		 RESULT = ""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CASOS_SWITCH_OPC",25, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // CASOS_SWITCH ::= CASOS_SWITCH CASO_SWITCH 
            {
              String RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String cs = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        RESULT = cs + "\n" + c;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CASOS_SWITCH",26, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // CASOS_SWITCH ::= CASO_SWITCH 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = c; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CASOS_SWITCH",26, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // CASO_SWITCH ::= Case VALOR DosPuntos LISTA_SENTENCIAS_OPC 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String cuerpo = s.isEmpty() ? "  <vacio>" : "  " + s.replace("\n", "\n  ");
        RESULT = "Case " + textoExpresion(v) + ":\n" + cuerpo;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CASO_SWITCH",27, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // DEFAULT_SWITCH_OPC ::= Default DosPuntos LISTA_SENTENCIAS_OPC 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String cuerpo = s.isEmpty() ? "  <vacio>" : "  " + s.replace("\n", "\n  ");
        RESULT = "Default:\n" + cuerpo;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DEFAULT_SWITCH_OPC",28, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // DEFAULT_SWITCH_OPC ::= 
            {
              String RESULT =null;
		 RESULT = ""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DEFAULT_SWITCH_OPC",28, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // SENTENCIA_IF ::= If Parentesis_a CONDICION Parentesis_c THEN_OPC MARCA_CI SENTENCIA 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		Integer m = (Integer)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String lfin = parser.getGenInter().nuevaEtiqueta();
        parser.getGenInter().insertarSaltoCondicionalFalso(m, valorExpresion(c), lfin);
        parser.getGenInter().agregarEtiqueta(lfin);
        RESULT = "If (" + textoExpresion(c) + ") " + s;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_IF",20, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // SENTENCIA_IF ::= If Parentesis_a CONDICION Parentesis_c THEN_OPC MARCA_CI SENTENCIA Else MARCA_CI SENTENCIA 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-7)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-7)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-7)).value;
		int m1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int m1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		Integer m1 = (Integer)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String s1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int m2left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int m2right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		Integer m2 = (Integer)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s2 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String lelse = parser.getGenInter().nuevaEtiqueta();
        String lfin = parser.getGenInter().nuevaEtiqueta();
        parser.getGenInter().insertarSaltoCondicionalFalso(m1, valorExpresion(c), lelse);
        int m2Ajustada = m2 + 1;
        parser.getGenInter().insertarSaltoIncondicional(m2Ajustada, lfin);
        parser.getGenInter().insertarInstruccion(m2Ajustada + 1, lelse + ":");
        parser.getGenInter().agregarEtiqueta(lfin);
        RESULT = "If (" + textoExpresion(c) + ") " + s1 + " else " + s2;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_IF",20, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-9)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // SENTENCIA_IF ::= If Parentesis_a Identificador Parentesis_c THEN_OPC SENTENCIA 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        RESULT = "If (" + id + ") " + s;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_IF",20, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-5)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // THEN_OPC ::= Then 
            {
              String RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("THEN_OPC",23, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // THEN_OPC ::= 
            {
              String RESULT =null;

              CUP$sintax$result = parser.getSymbolFactory().newSymbol("THEN_OPC",23, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // MARCA_CI ::= 
            {
              Integer RESULT =null;
		 RESULT = Integer.valueOf(parser.getGenInter().tamanoInstrucciones()); 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("MARCA_CI",29, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // SENTENCIA_WHILE ::= While Parentesis_a CONDICION Parentesis_c Do SENTENCIA EndWhile 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "While (" + textoExpresion(c) + ") do " + s + " endwhile";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_WHILE",21, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // SENTENCIA_WHILE ::= While Parentesis_a Identificador Parentesis_c Do SENTENCIA EndWhile 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        RESULT = "While (" + id + ") do " + s + " endwhile";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_WHILE",21, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // SENTENCIA_WHILE ::= While Parentesis_a CONDICION Parentesis_c Llave_a LISTA_SENTENCIAS_OPC Llave_c 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "While (" + textoExpresion(c) + ") {\n  "
                + (s.isEmpty() ? "<vacio>" : s.replace("\n", "\n  "))
                + "\n}";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_WHILE",21, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // SENTENCIA_WHILE ::= While Parentesis_a Identificador Parentesis_c Llave_a LISTA_SENTENCIAS_OPC Llave_c 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        RESULT = "While (" + id + ") {\n  "
                + (s.isEmpty() ? "<vacio>" : s.replace("\n", "\n  "))
                + "\n}";
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_WHILE",21, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-6)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // DECLARACION ::= TIPO_DATO Identificador 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String def = valorPorDefecto(t);
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, t, def, "local", idleft + 1));
        parser.getGenInter().agregarAsignacion(id, def);
        RESULT = "Declaracion: " + t + " " + id;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // DECLARACION ::= TIPO_DATO Identificador ASIGNADOR VALOR 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        parser.getTabla().agregar(new proyectofinalcompilador.Semantico.Simbolo(id, t, textoExpresion(v), "local", idleft + 1));
        parser.getGenInter().agregarAsignacion(id, valorExpresion(v));
        RESULT = "Declaracion: " + t + " " + id + " " + a + " " + textoExpresion(v);
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",11, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-3)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // ASIGNACION ::= Identificador ASIGNADOR VALOR 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        parser.getTabla().asignarValor(id, textoExpresion(e), idleft + 1);
        parser.getGenInter().agregarAsignacion(id, valorExpresion(e));
        RESULT = "Asignacion: " + id + " " + a + " " + textoExpresion(e);
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("ASIGNACION",12, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // VALOR ::= EXPRESION 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = e; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("VALOR",19, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // VALOR ::= Op_booleano 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = b + "::::" + b; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("VALOR",19, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // VALOR ::= Cadena 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = "\"" + c + "\"::::\"" + c + "\""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("VALOR",19, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ASIGNADOR ::= Igual 
            {
              String RESULT =null;
		 RESULT = "="; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("ASIGNADOR",13, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // ASIGNADOR ::= Op_atribucion 
            {
              String RESULT =null;
		int oaleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int oaright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String oa = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = oa; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("ASIGNADOR",13, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // TIPO_DATO ::= Int 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",18, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // TIPO_DATO ::= T_dato 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = t; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",18, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // TIPO_DATO ::= String_type 
            {
              String RESULT =null;
		 RESULT = "String"; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",18, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // CONDICION ::= EXPRESION Op_relacional EXPRESION 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        RESULT = textoExpresion(e1) + " " + op + " " + textoExpresion(e2) + "::::" + valorExpresion(e1) + " " + op + " " + valorExpresion(e2);
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",22, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // CONDICION ::= EXPRESION Igual EXPRESION 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        RESULT = textoExpresion(e1) + " = " + textoExpresion(e2) + "::::" + valorExpresion(e1) + " == " + valorExpresion(e2);
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",22, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // CONDICION ::= Op_booleano 
            {
              String RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = b + "::::" + b; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",22, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // CONDICION ::= Parentesis_a CONDICION Parentesis_c 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		 RESULT = "(" + textoExpresion(c) + ")::::(" + valorExpresion(c) + ")"; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONDICION",22, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // EXPRESION ::= EXPRESION Suma TERMINO 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, valorExpresion(e1), "+", valorExpresion(t1));
        RESULT = textoExpresion(e1) + " + " + textoExpresion(t1) + "::::" + temp;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",15, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // EXPRESION ::= EXPRESION Resta TERMINO 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, valorExpresion(e1), "-", valorExpresion(t1));
        RESULT = textoExpresion(e1) + " - " + textoExpresion(t1) + "::::" + temp;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",15, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // EXPRESION ::= TERMINO 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = t1; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",15, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // TERMINO ::= TERMINO Multiplicacion FACTOR 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int f1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String f1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, valorExpresion(t1), "*", valorExpresion(f1));
        RESULT = textoExpresion(t1) + " * " + textoExpresion(f1) + "::::" + temp;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",16, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // TERMINO ::= TERMINO Division FACTOR 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int f1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String f1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        String temp = parser.getGenInter().nuevaTemporal();
        parser.getGenInter().agregarOperacion(temp, valorExpresion(t1), "/", valorExpresion(f1));
        RESULT = textoExpresion(t1) + " / " + textoExpresion(f1) + "::::" + temp;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",16, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // TERMINO ::= FACTOR 
            {
              String RESULT =null;
		int f1left = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String f1 = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = f1; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",16, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // FACTOR ::= Numero 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = n + "::::" + n; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",17, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // FACTOR ::= Resta Numero 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = "-" + n + "::::-" + n; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",17, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // FACTOR ::= Identificador 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        parser.getTabla().verificarExistencia(id, idleft + 1);
        RESULT = id + "::::" + id;
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",17, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // FACTOR ::= Parentesis_a EXPRESION Parentesis_c 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-1)).value;
		
        RESULT = "(" + textoExpresion(e) + ")::::" + valorExpresion(e);
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",17, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // CONTENIDO_PARENTESIS ::= Cadena 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = "\"" + c + "\"::::\"" + c + "\""; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONTENIDO_PARENTESIS",14, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // CONTENIDO_PARENTESIS ::= Cadena Suma EXPRESION 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.elementAt(CUP$sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		
        RESULT = "\"" + c + "\" + " + textoExpresion(e) + "::::\"" + c + "\" + " + valorExpresion(e);
    
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONTENIDO_PARENTESIS",14, ((java_cup.runtime.Symbol)CUP$sintax$stack.elementAt(CUP$sintax$top-2)), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // CONTENIDO_PARENTESIS ::= EXPRESION 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$sintax$stack.peek()).value;
		 RESULT = e; 
              CUP$sintax$result = parser.getSymbolFactory().newSymbol("CONTENIDO_PARENTESIS",14, ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintax$stack.peek()), RESULT);
            }
          return CUP$sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$sintax$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$sintax$do_action(
    int                        CUP$sintax$act_num,
    java_cup.runtime.lr_parser CUP$sintax$parser,
    java.util.Stack            CUP$sintax$stack,
    int                        CUP$sintax$top)
    throws java.lang.Exception
    {
              return CUP$sintax$do_action_part00000000(
                               CUP$sintax$act_num,
                               CUP$sintax$parser,
                               CUP$sintax$stack,
                               CUP$sintax$top);
    }
}

}
