
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectofinalcompilador.Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 34;
  public static final int Class = 27;
  public static final int Op_booleano = 35;
  public static final int Llave_c = 19;
  public static final int Llave_a = 18;
  public static final int If = 5;
  public static final int Void = 29;
  public static final int T_dato = 32;
  public static final int Static = 28;
  public static final int Else = 6;
  public static final int Corchete_c = 21;
  public static final int Corchete_a = 20;
  public static final int Punto = 25;
  public static final int While = 8;
  public static final int Division = 14;
  public static final int Int = 4;
  public static final int Cadena = 38;
  public static final int Parentesis_c = 17;
  public static final int Parentesis_a = 16;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int P_coma = 23;
  public static final int error = 1;
  public static final int String_type = 30;
  public static final int Linea = 2;
  public static final int Op_atribucion = 36;
  public static final int Do = 7;
  public static final int ERROR = 24;
  public static final int Op_logico = 15;
  public static final int Public = 26;
  public static final int Identificador = 33;
  public static final int Resta = 12;
  public static final int Multiplicacion = 13;
  public static final int Op_incremento = 37;
  public static final int Numero = 31;
  public static final int Suma = 11;
  public static final int Main = 22;
  public static final int Igual = 10;
  public static final int Comillas = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Comillas",
  "Int",
  "If",
  "Else",
  "Do",
  "While",
  "For",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Op_logico",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "Main",
  "P_coma",
  "ERROR",
  "Punto",
  "Public",
  "Class",
  "Static",
  "Void",
  "String_type",
  "Numero",
  "T_dato",
  "Identificador",
  "Op_relacional",
  "Op_booleano",
  "Op_atribucion",
  "Op_incremento",
  "Cadena"
  };
}

